import { CafeItem, CuratedListType } from './types';

const IMAGES = {
  cafe1: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
  cafe2: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80',
  cafe3: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
  cafe4: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
  cafe5: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80',
  cafe6: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
  cafe7: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
  cafe8: 'https://images.unsplash.com/photo-1527030280862-64139fba04ca?auto=format&fit=crop&w=1200&q=80',
  cafe9: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80',
  cafe10: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80',
};

type CafeSeed = Omit<CafeItem, 'id' | 'createdAt' | 'reviews' | 'speedTests'>;

const base = (overrides: Partial<CafeSeed> & Pick<CafeSeed, 'name' | 'slug' | 'description' | 'address' | 'city' | 'lat' | 'lng'>): CafeSeed => ({
  tagline: overrides.tagline || overrides.description.slice(0, 80),
  neighborhood: null,
  phone: null,
  website: null,
  googlePlaceId: null,
  coverImage: IMAGES.cafe1,
  images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe2]),
  priceLevel: 2,
  hasWifi: true,
  wifiSpeedMbps: 50,
  wifiUploadMbps: 30,
  wifiReliability: 'STABLE',
  wifiPasswordNote: null,
  powerPlugDensity: 'MODERATE',
  noiseLevel: 'MODERATE',
  seatingCapacity: 'MEDIUM',
  seatingComfort: 'MIXED',
  lighting: 'BRIGHT',
  hasOutdoorSeating: false,
  isPetFriendly: false,
  hasCallBooths: false,
  hasMeetingRooms: false,
  hasParking: false,
  hasAirConditioning: true,
  hasRestrooms: true,
  openLate: false,
  specialtyCoffee: false,
  roasterName: null,
  foodOptions: 'LIGHT_BITES',
  veganOptions: false,
  status: 'VERIFIED',
  isVerified: true,
  openingHours: JSON.stringify({ monday: '8:00 AM – 9:00 PM', tuesday: '8:00 AM – 9:00 PM', wednesday: '8:00 AM – 9:00 PM', thursday: '8:00 AM – 9:00 PM', friday: '8:00 AM – 10:00 PM', saturday: '9:00 AM – 10:00 PM', sunday: '9:00 AM – 8:00 PM' }),
  averageRating: 4.3,
  reviewCount: 12,
  source: 'db',
  ...overrides,
});

export const initialCafes: CafeSeed[] = [

  // ── EXISTING 6 VERIFIED GLOBAL CAFES ──────────────────────────────────────

  base({
    name: 'The Assembly Working Cafe',
    slug: 'the-assembly-working-cafe-sf',
    tagline: 'Dedicated nomad tables, 280 Mbps fiber, ergonomic seating & artisan pour-overs.',
    description: 'Designed from the ground up for remote workers. Two zones: conversational front cafe and ultra-quiet greenhouse workspace with ergonomic chairs, power strips at every table, and 280 Mbps symmetric fiber.',
    address: '3232 22nd St, San Francisco, CA 94110',
    city: 'San Francisco', neighborhood: 'Mission District',
    lat: 37.75547, lng: -122.42149,
    phone: '+1 (415) 890-3412', website: 'https://theassembly-sf.example.com',
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe2, IMAGES.cafe7]),
    wifiSpeedMbps: 284.5, wifiUploadMbps: 210, wifiReliability: 'ROCK_SOLID',
    wifiPasswordNote: 'Printed on receipt / open guest network at front tables',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'QUIET', seatingCapacity: 'LARGE', seatingComfort: 'ERGONOMIC', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, hasCallBooths: true, hasMeetingRooms: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Sightglass Coffee & Onyx Coffee Lab', foodOptions: 'FULL_MENU', veganOptions: true,
    openingHours: JSON.stringify({ monday: '7:00 AM – 10:00 PM', tuesday: '7:00 AM – 10:00 PM', wednesday: '7:00 AM – 10:00 PM', thursday: '7:00 AM – 10:00 PM', friday: '7:00 AM – 11:00 PM', saturday: '8:00 AM – 11:00 PM', sunday: '8:00 AM – 9:00 PM' }),
    averageRating: 4.8, reviewCount: 48,
  }),

  base({
    name: 'Hearth & Loom Workspace Lab',
    slug: 'hearth-loom-workspace-brooklyn',
    tagline: 'Williamsburg loft: gigabit mesh, phone pods & library-quiet upper floor.',
    description: 'Converted industrial loft in Williamsburg with high ceilings, floor-to-ceiling windows, and gigabit mesh WiFi. Famous for its dedicated silent study room on the mezzanine.',
    address: '182 Bedford Ave, Brooklyn, NY 11211',
    city: 'New York', neighborhood: 'Williamsburg',
    lat: 40.71780, lng: -73.95726,
    phone: '+1 (718) 555-0192',
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    wifiSpeedMbps: 340, wifiUploadMbps: 290, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingCapacity: 'SPACIOUS', seatingComfort: 'ERGONOMIC', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, hasCallBooths: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Sey Coffee', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.9, reviewCount: 62,
  }),

  base({
    name: 'Kurasu Kyoto Roastery',
    slug: 'kurasu-kyoto-roastery',
    tagline: 'Minimalist Japanese aesthetics, Kyoto cold brew, deep contemplative focus.',
    description: 'Quiet specialty coffee bar in a converted Kyoto machiya townhouse near Kyoto Station. Perfect for deep work and technical writing.',
    address: '552 Higashishiokojicho, Shimogyo Ward, Kyoto 600-8214',
    city: 'Kyoto', neighborhood: 'Shimogyo / Kyoto Station',
    lat: 34.98582, lng: 135.75881,
    phone: '+81 75-744-0804', website: 'https://kurasu.kyoto',
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe5]),
    wifiSpeedMbps: 185, wifiUploadMbps: 120, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'SILENT', lighting: 'BRIGHT',
    specialtyCoffee: true, roasterName: 'Kurasu In-House Roastery', foodOptions: 'PASTRIES', veganOptions: true,
    openingHours: JSON.stringify({ monday: '8:00 AM – 7:00 PM', tuesday: '8:00 AM – 7:00 PM', wednesday: '8:00 AM – 7:00 PM', thursday: '8:00 AM – 7:00 PM', friday: '8:00 AM – 7:00 PM', saturday: '8:00 AM – 7:00 PM', sunday: '8:00 AM – 7:00 PM' }),
    averageRating: 4.9, reviewCount: 34,
  }),

  base({
    name: 'Dojo Bali Cowork & Cafe',
    slug: 'dojo-bali-canggu',
    tagline: "Canggu's original nomad hub: dual Starlink, call pods & cold brew on tap.",
    description: 'Original digital nomad destination in Canggu. Dual Starlink + fiber backup, standing desks, AC private call pods, and Anomali specialty espresso.',
    address: 'Jl. Batu Mejan No.88, Canggu, Bali 80351',
    city: 'Bali', neighborhood: 'Canggu',
    lat: -8.65062, lng: 115.13180,
    phone: '+62 812-3456-7890', website: 'https://www.dojobali.org',
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 215, wifiUploadMbps: 85, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', seatingCapacity: 'SPACIOUS', seatingComfort: 'ERGONOMIC', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, hasCallBooths: true, hasMeetingRooms: true, hasParking: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Anomali Coffee', foodOptions: 'FULL_MENU', veganOptions: true,
    openingHours: JSON.stringify({ monday: '7:00 AM – 11:00 PM', tuesday: '7:00 AM – 11:00 PM', wednesday: '7:00 AM – 11:00 PM', thursday: '7:00 AM – 11:00 PM', friday: '7:00 AM – 11:00 PM', saturday: '7:00 AM – 11:00 PM', sunday: '7:00 AM – 11:00 PM' }),
    averageRating: 4.7, reviewCount: 92,
  }),

  base({
    name: 'Patika Coffee — South Lamar',
    slug: 'patika-coffee-south-congress-austin',
    tagline: 'Pecan-shaded patio, plentiful power strips & Turkish-inspired specialty coffee.',
    description: 'Austin\'s South Lamar gem with weatherproof power strips, a quiet study lounge, and Turkish-style specialty espresso. Free parking lot.',
    address: '2159 S Lamar Blvd, Austin, TX 78704',
    city: 'Austin', neighborhood: 'South Lamar',
    lat: 30.24877, lng: -97.76602,
    phone: '+1 (512) 441-2300', website: 'https://patikacoffee.com',
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe6]),
    wifiSpeedMbps: 165, wifiUploadMbps: 140, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', seatingCapacity: 'LARGE', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, hasParking: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Flat Track Coffee', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.6, reviewCount: 39,
  }),

  base({
    name: 'The Barn — Prenzlauer Berg',
    slug: 'the-barn-berlin-prenzlauer',
    tagline: 'Nordic light roast pioneers, warm timber study tables & laser-focused quiet.',
    description: 'Berlin\'s definitive third-wave coffee institution. Rear timber study tables, solid WiFi, calm atmosphere for deep async work.',
    address: 'Schönhauser Allee 8, 10119 Berlin, Germany',
    city: 'Berlin', neighborhood: 'Prenzlauer Berg',
    lat: 52.53124, lng: 13.41163,
    phone: '+49 30 55578912', website: 'https://thebarn.de',
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe3]),
    wifiSpeedMbps: 195, wifiUploadMbps: 95, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'BASIC', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true,
    specialtyCoffee: true, roasterName: 'The Barn In-house Nordic Roastery', foodOptions: 'PASTRIES', veganOptions: true,
    openingHours: JSON.stringify({ monday: '8:00 AM – 6:00 PM', tuesday: '8:00 AM – 6:00 PM', wednesday: '8:00 AM – 6:00 PM', thursday: '8:00 AM – 6:00 PM', friday: '8:00 AM – 6:00 PM', saturday: '9:00 AM – 6:00 PM', sunday: '9:00 AM – 6:00 PM' }),
    averageRating: 4.7, reviewCount: 51,
  }),

  // ── INDIA ─────────────────────────────────────────────────────────────────

  base({
    name: 'Kala Ghoda Cafe', slug: 'kala-ghoda-cafe-mumbai',
    tagline: 'Iconic Mumbai heritage cafe in the art district with great filter coffee.',
    description: 'A beloved institution in Mumbai\'s art district, Kala Ghoda Cafe serves excellent filter coffee and a menu of sandwiches and desserts. Popular with creatives, writers, and remote workers for its relaxed vibe and reliable WiFi.',
    address: '10, Ropewalk Lane, Kala Ghoda, Fort, Mumbai 400001',
    city: 'Mumbai', neighborhood: 'Kala Ghoda / Fort',
    lat: 18.92850, lng: 72.83180,
    phone: '+91 22-2267-0860', website: 'https://kalaghodacafe.com',
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe1]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', lighting: 'DIM_COZY',
    hasOutdoorSeating: true, specialtyCoffee: false, foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.4, reviewCount: 28,
  }),

  base({
    name: 'Third Wave Coffee — Andheri', slug: 'third-wave-coffee-andheri-mumbai',
    tagline: 'Mumbai\'s specialty chain: fast WiFi, ergonomic seating and single-origin pour-overs.',
    description: 'Part of India\'s fastest-growing specialty coffee chain, this Andheri outpost has reliable high-speed WiFi, ergonomic chairs, and ample power outlets — a favourite among Mumbai developers and startup founders.',
    address: 'Veera Desai Rd, Andheri West, Mumbai 400053',
    city: 'Mumbai', neighborhood: 'Andheri West',
    lat: 19.11960, lng: 72.84690,
    website: 'https://thirdwavecoffee.in',
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe2]),
    wifiSpeedMbps: 80, wifiUploadMbps: 40, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, specialtyCoffee: true, roasterName: 'Third Wave Coffee Roasters', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.5, reviewCount: 35,
  }),

  base({
    name: 'Woodside Inn', slug: 'woodside-inn-colaba-mumbai',
    tagline: 'Colaba gastropub with fast WiFi, all-day menu and a work-friendly vibe.',
    description: 'A Colaba institution with reliably fast WiFi, a full all-day menu, and the kind of buzzy-but-focused atmosphere that suits remote workers and journalists. Power outlets at most booths.',
    address: 'Colaba Causeway, Colaba, Mumbai 400005',
    city: 'Mumbai', neighborhood: 'Colaba',
    lat: 18.92320, lng: 72.83000,
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe5]),
    priceLevel: 3, wifiSpeedMbps: 55, wifiUploadMbps: 25, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'LIVELY', lighting: 'DIM_COZY',
    openLate: true, foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.2, reviewCount: 19,
  }),

  base({
    name: 'Blue Tokai Coffee — Lodhi Colony', slug: 'blue-tokai-lodhi-colony-delhi',
    tagline: 'Delhi\'s top specialty roastery cafe: fast WiFi and Indian single-origins.',
    description: 'Blue Tokai\'s Lodhi Colony outpost is Delhi\'s go-to for serious coffee enthusiasts and remote workers. Roasts its own Indian single-origin beans and offers outstanding pour-overs with reliable high-speed WiFi.',
    address: '6, Lodhi Colony Market, New Delhi 110003',
    city: 'Delhi', neighborhood: 'Lodhi Colony',
    lat: 28.59000, lng: 77.22700,
    phone: '+91 11-4353-9500', website: 'https://bluetokaicoffee.com',
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe9]),
    wifiSpeedMbps: 90, wifiUploadMbps: 50, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    specialtyCoffee: true, roasterName: 'Blue Tokai Coffee Roasters', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.7, reviewCount: 44,
  }),

  base({
    name: 'Third Wave Coffee — Connaught Place', slug: 'third-wave-coffee-cp-delhi',
    tagline: 'Central Delhi specialty hub with fast WiFi and all-day food menu.',
    description: 'Conveniently located in the heart of Connaught Place, this Third Wave Coffee outlet is a favourite for Delhi\'s tech workers, freelancers, and startup teams. High-speed WiFi and ergonomic chairs throughout.',
    address: 'N-Block, Connaught Place, New Delhi 110001',
    city: 'Delhi', neighborhood: 'Connaught Place',
    lat: 28.63150, lng: 77.21670,
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe7]),
    wifiSpeedMbps: 75, wifiUploadMbps: 35, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Third Wave Coffee Roasters', foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.5, reviewCount: 31,
  }),

  base({
    name: 'Matteo Coffea', slug: 'matteo-coffea-bangalore',
    tagline: 'Bengaluru\'s cult specialty espresso bar — minimal, fast, and distraction-free.',
    description: 'A cult favourite among Bengaluru\'s developer community, Matteo Coffea is a standing-bar espresso counter with exceptional Italian-style coffee, fast complementary WiFi, and a no-nonsense productive atmosphere.',
    address: '12, Church St, Shanthala Nagar, Bengaluru 560001',
    city: 'Bengaluru', neighborhood: 'Church Street / MG Road',
    lat: 12.97820, lng: 77.59670,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe3]),
    priceLevel: 2, wifiSpeedMbps: 60, wifiUploadMbps: 30, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'QUIET',
    specialtyCoffee: true, roasterName: 'Matteo In-House', foodOptions: 'PASTRIES',
    openingHours: JSON.stringify({ monday: '7:30 AM – 7:00 PM', tuesday: '7:30 AM – 7:00 PM', wednesday: '7:30 AM – 7:00 PM', thursday: '7:30 AM – 7:00 PM', friday: '7:30 AM – 7:00 PM', saturday: '8:00 AM – 7:00 PM', sunday: '8:00 AM – 6:00 PM' }),
    averageRating: 4.6, reviewCount: 38,
  }),

  base({
    name: 'Blue Tokai Coffee — Indiranagar', slug: 'blue-tokai-indiranagar-bangalore',
    tagline: 'Bengaluru tech hub: Indian single-origins, fast WiFi, all-day seating.',
    description: 'Indiranagar\'s most popular remote-work cafe. Blue Tokai serves its own Indian single-origin beans with strong WiFi and plentiful power outlets. Packed with startup founders, engineers, and UX designers on weekdays.',
    address: '100 Feet Road, Indiranagar, Bengaluru 560038',
    city: 'Bengaluru', neighborhood: 'Indiranagar',
    lat: 12.97830, lng: 77.64120,
    website: 'https://bluetokaicoffee.com',
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe6]),
    wifiSpeedMbps: 95, wifiUploadMbps: 55, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Blue Tokai Coffee Roasters', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.6, reviewCount: 52,
  }),

  base({
    name: 'Dyu Art Cafe', slug: 'dyu-art-cafe-bangalore',
    tagline: 'Koramangala garden cafe for creatives — great filter coffee and calm garden seating.',
    description: 'A beloved Koramangala cafe with a lush garden patio, local artwork on every wall, and exceptional South Indian filter coffee. Very popular with designers, writers, and remote teams for long afternoon working sessions.',
    address: '23, 1st Cross, Koramangala 5th Block, Bengaluru 560095',
    city: 'Bengaluru', neighborhood: 'Koramangala',
    lat: 12.93290, lng: 77.62760,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 40, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, veganOptions: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 29,
  }),

  base({
    name: 'Vohuman Cafe', slug: 'vohuman-cafe-pune',
    tagline: 'Pune\'s iconic Irani cafe — legendary bun maska, Irani chai, and old-world charm.',
    description: 'A Pune landmark since 1953, Vohuman Cafe serves legendary bun maska and Irani chai in a charming no-frills setting. Visited by students, journalists, and professionals. WiFi is basic but the productive vibe is unmatched.',
    address: 'Sassoon Road, Near Railway Station, Pune 411001',
    city: 'Pune', neighborhood: 'Camp / Railway Station',
    lat: 18.53140, lng: 73.87740,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 15, wifiUploadMbps: 5, wifiReliability: 'SPOTTY',
    powerPlugDensity: 'SCARCE', noiseLevel: 'LIVELY', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    openingHours: JSON.stringify({ monday: '6:00 AM – 11:30 PM', tuesday: '6:00 AM – 11:30 PM', wednesday: '6:00 AM – 11:30 PM', thursday: '6:00 AM – 11:30 PM', friday: '6:00 AM – 11:30 PM', saturday: '6:00 AM – 11:30 PM', sunday: '6:00 AM – 11:30 PM' }),
    averageRating: 4.5, reviewCount: 67,
  }),

  base({
    name: 'Pagdandi Books Chai Cafe', slug: 'pagdandi-books-chai-cafe-pune',
    tagline: 'Pune\'s beloved bookshop-cafe — chai, books, and a quiet space to work.',
    description: 'A tucked-away Baner gem combining a bookshop with an excellent chai and snacks menu. Warm wooden interiors, slow music, and a genuinely quiet reading-and-working atmosphere. Great for writers and students.',
    address: 'Baner Road, Baner, Pune 411045',
    city: 'Pune', neighborhood: 'Baner',
    lat: 18.56790, lng: 73.77650,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe3]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', lighting: 'DIM_COZY',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.6, reviewCount: 22,
  }),

  base({
    name: 'Roastery Coffee House', slug: 'roastery-coffee-house-hyderabad',
    tagline: 'Hyderabad\'s top specialty roaster — Jubilee Hills outpost with fast WiFi.',
    description: 'Roastery Coffee House is Hyderabad\'s premium specialty coffee destination. The Jubilee Hills location has comfortable seating, reliable WiFi, and baristas who can talk you through the origin of every bean.',
    address: 'Road No. 36, Jubilee Hills, Hyderabad 500033',
    city: 'Hyderabad', neighborhood: 'Jubilee Hills',
    lat: 17.42700, lng: 78.44850,
    website: 'https://roasterycoffeehouse.com',
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe1]),
    wifiSpeedMbps: 70, wifiUploadMbps: 35, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, specialtyCoffee: true, roasterName: 'Roastery Coffee House', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.7, reviewCount: 41,
  }),

  base({
    name: 'Amethyst Cafe', slug: 'amethyst-cafe-chennai',
    tagline: 'Chennai\'s most beautiful garden cafe — bougainvillea courtyards and great wifi.',
    description: 'Set in a restored heritage bungalow in Royapettah, Amethyst is one of Chennai\'s most beloved cafes. Lush bougainvillea-covered courtyards, excellent coffee, and reliable WiFi make it ideal for afternoon work sessions.',
    address: 'Whites Road, Royapettah, Chennai 600014',
    city: 'Chennai', neighborhood: 'Royapettah',
    lat: 13.05400, lng: 80.25100,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe5]),
    priceLevel: 3, wifiSpeedMbps: 55, wifiUploadMbps: 25, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, specialtyCoffee: true, foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.6, reviewCount: 33,
  }),

  base({
    name: 'Flurys — Park Street', slug: 'flurys-park-street-kolkata',
    tagline: 'Kolkata\'s iconic 1927 Swiss patisserie-cafe — history meets great coffee.',
    description: 'A Kolkata institution since 1927, Flurys on Park Street blends colonial-era elegance with modern specialty drinks. Excellent for morning work sessions with its calm ambience, strong coffee, and legendary patisseries.',
    address: '18, Park Street, Kolkata 700016',
    city: 'Kolkata', neighborhood: 'Park Street',
    lat: 22.55100, lng: 88.35200,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe10]),
    priceLevel: 2, wifiSpeedMbps: 40, wifiUploadMbps: 18, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'DIM_COZY',
    specialtyCoffee: false, foodOptions: 'FULL_MENU', veganOptions: false,
    openingHours: JSON.stringify({ monday: '7:30 AM – 9:00 PM', tuesday: '7:30 AM – 9:00 PM', wednesday: '7:30 AM – 9:00 PM', thursday: '7:30 AM – 9:00 PM', friday: '7:30 AM – 9:00 PM', saturday: '7:30 AM – 9:00 PM', sunday: '7:30 AM – 9:00 PM' }),
    averageRating: 4.3, reviewCount: 55,
  }),

  base({
    name: 'Artjuna Garden Cafe', slug: 'artjuna-garden-cafe-goa',
    tagline: 'Arambol\'s hippie-chic garden cafe — fresh juices, veggie bowls, nomad community.',
    description: 'Set in a tropical garden in Arambol, Artjuna is a global digital nomad gathering point. Organic food, fresh juices, great smoothie bowls, and a community bulletin board full of events. WiFi is decent for Goa.',
    address: 'Girkar Waddo, Arambol, Goa 403524',
    city: 'Goa', neighborhood: 'Arambol',
    lat: 15.68700, lng: 73.71700,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe7]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'SPOTTY',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.4, reviewCount: 47,
  }),

  base({
    name: 'Brewbot Eatery & Pub', slug: 'brewbot-eatery-baga-goa',
    tagline: 'Baga\'s microbrewery with fast WiFi, large tables and power-friendly booths.',
    description: 'Goa\'s popular Baga microbrewery with strong WiFi, large communal tables, and dedicated power outlets near most seating sections. A great daytime working spot before it gets busy in the evenings.',
    address: 'Baga Creek Rd, Calangute, Goa 403516',
    city: 'Goa', neighborhood: 'Baga',
    lat: 15.55790, lng: 73.75060,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe2]),
    priceLevel: 3, wifiSpeedMbps: 50, wifiUploadMbps: 22, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'LIVELY', openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.2, reviewCount: 26,
  }),

  base({
    name: 'Curious Life Coffee Roasters', slug: 'curious-life-coffee-jaipur',
    tagline: 'Jaipur\'s first serious specialty roastery with fast WiFi and minimalist vibe.',
    description: 'Jaipur\'s standout specialty coffee shop, roasting its own beans and taking pour-over craft seriously. Clean minimal interior, reliable WiFi, and a focused crowd of creatives and developers on weekdays.',
    address: 'C-Scheme, Jaipur 302001',
    city: 'Jaipur', neighborhood: 'C-Scheme',
    lat: 26.91240, lng: 75.78730,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe5]),
    wifiSpeedMbps: 55, wifiUploadMbps: 28, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    specialtyCoffee: true, roasterName: 'Curious Life Roasters', foodOptions: 'PASTRIES', veganOptions: true,
    averageRating: 4.5, reviewCount: 18,
  }),

  base({
    name: 'Cafe Niloufer', slug: 'cafe-niloufer-hyderabad',
    tagline: 'Hyderabad\'s historic Irani cafe — Osmania biscuits, chai & laid-back work sessions.',
    description: 'One of Hyderabad\'s oldest Irani cafes near Abids, famous for its Osmania biscuits and thick chai. A no-laptop-time-limit policy and laid-back management make it a popular choice for students and writers.',
    address: 'Bank Street, Abids, Hyderabad 500001',
    city: 'Hyderabad', neighborhood: 'Abids',
    lat: 17.38650, lng: 78.47410,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'SPOTTY',
    powerPlugDensity: 'SCARCE', noiseLevel: 'LIVELY', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    openingHours: JSON.stringify({ monday: '7:00 AM – 10:00 PM', tuesday: '7:00 AM – 10:00 PM', wednesday: '7:00 AM – 10:00 PM', thursday: '7:00 AM – 10:00 PM', friday: '7:00 AM – 10:00 PM', saturday: '7:00 AM – 10:00 PM', sunday: '7:00 AM – 10:00 PM' }),
    averageRating: 4.3, reviewCount: 61,
  }),

  base({
    name: 'Kochi Coffee House', slug: 'kochi-coffee-house-kerala',
    tagline: 'Fort Kochi harbour-view cafe — Kerala filter kaapi and relaxed work afternoons.',
    description: 'A relaxed cafe in the heritage Fort Kochi area with harbour views, strong Kerala filter kaapi, and decent WiFi. Popular with travellers and remote workers exploring southern India.',
    address: 'Parade Ground, Fort Kochi, Kochi 682001',
    city: 'Kochi', neighborhood: 'Fort Kochi',
    lat: 9.96500, lng: 76.24300,
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.3, reviewCount: 23,
  }),

  // ── RATNAGIRI (user's city) ────────────────────────────────────────────────

  base({
    name: 'Cafe Landmark — Ratnagiri', slug: 'cafe-landmark-ratnagiri',
    tagline: 'Ratnagiri\'s go-to cafe for filter coffee, vada pav and afternoon study sessions.',
    description: 'A popular spot near Ratnagiri town centre frequented by local college students, professionals, and travellers. Serves South Indian filter coffee, vada pav, and light snacks with WiFi available to patrons.',
    address: 'Near RTO Office, Nachane Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Nachane Road',
    lat: 16.99020, lng: 73.31200,
    phone: '+91 98765-43210',
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe6]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    openingHours: JSON.stringify({ monday: '7:00 AM – 9:00 PM', tuesday: '7:00 AM – 9:00 PM', wednesday: '7:00 AM – 9:00 PM', thursday: '7:00 AM – 9:00 PM', friday: '7:00 AM – 9:00 PM', saturday: '7:00 AM – 9:00 PM', sunday: '8:00 AM – 8:00 PM' }),
    averageRating: 4.1, reviewCount: 14,
  }),

  base({
    name: 'Hotel Abhimanyu Cafe', slug: 'hotel-abhimanyu-cafe-ratnagiri',
    tagline: 'Clean, air-conditioned cafe near Ratnagiri bus stand — reliable stop for nomads.',
    description: 'Conveniently located near the Ratnagiri bus stand and railway station, Hotel Abhimanyu\'s cafe is a clean, air-conditioned space with South Indian meals, chai, and usable WiFi — a good stop for remote workers travelling the Konkan coast.',
    address: 'Near Bus Stand, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Bus Stand Area',
    lat: 16.98760, lng: 73.31350,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe3]),
    priceLevel: 1, wifiSpeedMbps: 15, wifiUploadMbps: 6, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'FULL_MENU',
    averageRating: 3.9, reviewCount: 9,
  }),

  // ── ASIA-PACIFIC ──────────────────────────────────────────────────────────

  base({
    name: 'Chye Seng Huat Hardware Coffee', slug: 'chye-seng-huat-singapore',
    tagline: 'Singapore\'s iconic hardware store turned third-wave cafe — incredible espresso.',
    description: 'Housed in a restored 1950s hardware shop in Jalan Besar, CSHH is one of Singapore\'s finest specialty coffee destinations. Excellent espresso program, fast WiFi, and an airy industrial space perfect for working.',
    address: '150 Tyrwhitt Rd, Singapore 207563',
    city: 'Singapore', neighborhood: 'Jalan Besar',
    lat: 1.31070, lng: 103.85580,
    website: 'https://cshhcoffee.com',
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    priceLevel: 2, wifiSpeedMbps: 200, wifiUploadMbps: 150, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, specialtyCoffee: true, roasterName: 'CSHH In-house', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.7, reviewCount: 58,
  }),

  base({
    name: 'Fuglen Tokyo', slug: 'fuglen-tokyo-tomigaya',
    tagline: 'Norwegian cafe institution in Tokyo — ultra-precise espresso and calm workspace.',
    description: 'Oslo\'s iconic Fuglen brought its award-winning coffee program and Nordic calm to Tokyo\'s Tomigaya neighbourhood. Near-silent working atmosphere, exceptional filter coffee, and fast Japanese fibre WiFi.',
    address: '1-16-11 Tomigaya, Shibuya, Tokyo 151-0063',
    city: 'Tokyo', neighborhood: 'Tomigaya / Shibuya',
    lat: 35.66570, lng: 139.70680,
    website: 'https://fuglen.com/tokyo',
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe7]),
    priceLevel: 2, wifiSpeedMbps: 300, wifiUploadMbps: 250, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    specialtyCoffee: true, roasterName: 'Fuglen Oslo', foodOptions: 'PASTRIES',
    openingHours: JSON.stringify({ monday: '8:00 AM – 10:00 PM', tuesday: '8:00 AM – 10:00 PM', wednesday: '8:00 AM – 10:00 PM', thursday: '8:00 AM – 10:00 PM', friday: '8:00 AM – 12:00 AM', saturday: '9:00 AM – 12:00 AM', sunday: '9:00 AM – 10:00 PM' }),
    averageRating: 4.8, reviewCount: 44,
  }),

  base({
    name: '% Arabica — Dubai Mall', slug: 'percent-arabica-dubai-mall',
    tagline: 'Dubai\'s most photogenic specialty cafe — Japanese-style espresso in the desert.',
    description: 'The iconic Japanese specialty coffee chain % Arabica brings its minimalist aesthetic and world-class espresso to Dubai Mall. Blazing fast mall WiFi, ergonomic bar seating, and air conditioning make it surprisingly work-friendly.',
    address: 'Dubai Mall, Financial Centre Road, Dubai, UAE',
    city: 'Dubai', neighborhood: 'Downtown Dubai',
    lat: 25.19880, lng: 55.27330,
    website: 'https://arabica.coffee',
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe4]),
    priceLevel: 3, wifiSpeedMbps: 250, wifiUploadMbps: 200, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'MODERATE', noiseLevel: 'LIVELY', seatingComfort: 'MIXED',
    hasAirConditioning: true, specialtyCoffee: true, roasterName: '% Arabica', foodOptions: 'PASTRIES',
    averageRating: 4.5, reviewCount: 37,
  }),

  base({
    name: 'Proud Mary Coffee Roasters', slug: 'proud-mary-coffee-melbourne',
    tagline: 'Melbourne specialty institution: extraordinary espresso & serious work ethic.',
    description: 'One of Melbourne\'s most celebrated coffee roasters and cafes in Collingwood. Proud Mary sources exceptional lots from around the world. Fast NBN WiFi, communal work tables, and Australia\'s finest espresso.',
    address: '172 Oxford St, Collingwood VIC 3066, Australia',
    city: 'Melbourne', neighborhood: 'Collingwood',
    lat: -37.80440, lng: 144.97880,
    website: 'https://proudmarycoffee.com.au',
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe1]),
    wifiSpeedMbps: 180, wifiUploadMbps: 90, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    specialtyCoffee: true, roasterName: 'Proud Mary Roasters', foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.8, reviewCount: 63,
  }),

  base({
    name: 'Single O — Surry Hills', slug: 'single-o-surry-hills-sydney',
    tagline: 'Sydney\'s first specialty roaster — origin-forward coffee and fast NBN WiFi.',
    description: 'Pioneering Australian specialty roaster, Single O has been pushing coffee standards since 2003. The Surry Hills mothership has fast WiFi, comfortable seating, and exceptional filter and espresso options.',
    address: '60-64 Reservoir St, Surry Hills NSW 2010, Australia',
    city: 'Sydney', neighborhood: 'Surry Hills',
    lat: -33.89350, lng: 151.20350,
    website: 'https://singleocoffee.com',
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe2]),
    wifiSpeedMbps: 160, wifiUploadMbps: 80, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    specialtyCoffee: true, roasterName: 'Single O Roasters', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.7, reviewCount: 49,
  }),

  // ── EUROPE ────────────────────────────────────────────────────────────────

  base({
    name: 'Monmouth Coffee — Borough Market', slug: 'monmouth-coffee-borough-london',
    tagline: 'London\'s finest filter coffee institution — Borough Market heritage since 1978.',
    description: 'A London coffee institution since 1978. The Borough Market branch has communal wooden tables, excellent filter coffee sourced directly from farmers, and fast WiFi. Perfect for morning focused work sessions.',
    address: '2 Park St, London SE1 9AB, United Kingdom',
    city: 'London', neighborhood: 'Borough Market / Southwark',
    lat: 51.50550, lng: -0.09090,
    website: 'https://monmouthcoffee.co.uk',
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe3]),
    priceLevel: 2, wifiSpeedMbps: 120, wifiUploadMbps: 60, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    specialtyCoffee: true, roasterName: 'Monmouth Coffee', foodOptions: 'PASTRIES',
    openingHours: JSON.stringify({ monday: '7:30 AM – 6:00 PM', tuesday: '7:30 AM – 6:00 PM', wednesday: '7:30 AM – 6:00 PM', thursday: '7:30 AM – 6:00 PM', friday: '7:30 AM – 6:00 PM', saturday: '8:00 AM – 6:00 PM', sunday: 'Closed' }),
    averageRating: 4.7, reviewCount: 72,
  }),

  base({
    name: 'Attendant Coffee Roasters', slug: 'attendant-coffee-fitzrovia-london',
    tagline: 'Victorian public toilet turned award-winning London specialty cafe.',
    description: 'Housed in a converted Victorian public toilet in Fitzrovia, Attendant serves exceptional espresso and filter coffee in a truly unique setting. Fast WiFi and comfortable seating. A must-visit for coffee-touring nomads.',
    address: '27A Foley St, London W1W 6DY, United Kingdom',
    city: 'London', neighborhood: 'Fitzrovia',
    lat: 51.51930, lng: -0.13600,
    website: 'https://the-attendant.com',
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe7]),
    priceLevel: 2, wifiSpeedMbps: 100, wifiUploadMbps: 50, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'BASIC',
    specialtyCoffee: true, roasterName: 'Attendant Roasters', foodOptions: 'PASTRIES', veganOptions: true,
    averageRating: 4.6, reviewCount: 41,
  }),

  base({
    name: 'Café de Flore', slug: 'cafe-de-flore-paris',
    tagline: 'Paris\'s most iconic literary cafe — Sartre\'s table and superb café au lait.',
    description: 'One of the oldest and most prestigious cafes in Paris, where existentialists debated and Picasso painted. Café de Flore still attracts writers, philosophers, and professionals with its timeless atmosphere and excellent café au lait.',
    address: '172 Boulevard Saint-Germain, 75006 Paris, France',
    city: 'Paris', neighborhood: 'Saint-Germain-des-Prés',
    lat: 48.85420, lng: 2.33300,
    website: 'https://cafedeflore.fr',
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe4]),
    priceLevel: 3, wifiSpeedMbps: 80, wifiUploadMbps: 40, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'LIVELY', seatingComfort: 'COZY_COUCHES',
    hasOutdoorSeating: true, foodOptions: 'FULL_MENU',
    openingHours: JSON.stringify({ monday: '7:30 AM – 1:30 AM', tuesday: '7:30 AM – 1:30 AM', wednesday: '7:30 AM – 1:30 AM', thursday: '7:30 AM – 1:30 AM', friday: '7:30 AM – 1:30 AM', saturday: '7:30 AM – 1:30 AM', sunday: '7:30 AM – 1:30 AM' }),
    averageRating: 4.3, reviewCount: 88,
  }),

  base({
    name: 'Back to Black Coffee', slug: 'back-to-black-amsterdam',
    tagline: 'Amsterdam specialty roastery — Nordic-style brews in the De Pijp canal neighbourhood.',
    description: 'A standout Amsterdam specialty cafe and roastery in De Pijp known for its Nordic-influenced filter brewing and direct-trade sourcing. Fast fibre WiFi, communal brew bar seating, and a focused working atmosphere.',
    address: 'Weteringstraat 48, 1017 SN Amsterdam, Netherlands',
    city: 'Amsterdam', neighborhood: 'De Pijp',
    lat: 52.36450, lng: 4.88950,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe6]),
    priceLevel: 2, wifiSpeedMbps: 150, wifiUploadMbps: 100, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'MIXED',
    specialtyCoffee: true, roasterName: 'Back to Black Roasters', foodOptions: 'PASTRIES', veganOptions: true,
    averageRating: 4.6, reviewCount: 34,
  }),

  // ── AMERICAS ──────────────────────────────────────────────────────────────

  base({
    name: 'Sam James Coffee Bar — Harbord', slug: 'sam-james-coffee-bar-toronto',
    tagline: 'Toronto\'s minimalist specialty bar — exceptional espresso and laser focus.',
    description: 'Toronto\'s cult-favourite minimalist espresso bar in the Annex neighbourhood. Sam James Coffee Bar serves some of Canada\'s best espresso in a no-laptop-discouraged environment — the focused vibe is naturally productive.',
    address: '297 Harbord St, Toronto, ON M6G 1G7, Canada',
    city: 'Toronto', neighborhood: 'Harbord / The Annex',
    lat: 43.66820, lng: -79.39280,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe9]),
    priceLevel: 2, wifiSpeedMbps: 120, wifiUploadMbps: 60, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET',
    specialtyCoffee: true, roasterName: 'Sam James Roasters', foodOptions: 'PASTRIES',
    averageRating: 4.7, reviewCount: 39,
  }),

  base({
    name: 'Truth Coffee Roasting', slug: 'truth-coffee-roasting-cape-town',
    tagline: 'Cape Town\'s steampunk coffee cathedral — voted world\'s best cafe.',
    description: 'Voted the world\'s best coffee shop multiple times, Truth Coffee Roasting in Cape Town is a steampunk-themed coffee cathedral. Exceptional espresso, roasting on-site, fast WiFi, and a truly inspiring workspace.',
    address: '36 Buitenkant St, Cape Town City Centre, 8001, South Africa',
    city: 'Cape Town', neighborhood: 'City Centre',
    lat: -33.92520, lng: 18.42370,
    website: 'https://truth.coffee',
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 80, wifiUploadMbps: 40, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, specialtyCoffee: true, roasterName: 'Truth Coffee Roasting', foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.8, reviewCount: 91,
  }),

  base({
    name: 'Fritz Coffee Company', slug: 'fritz-coffee-seoul',
    tagline: 'Seoul\'s most celebrated indie roastery — Danish-influenced cafe in Mapo.',
    description: 'Fritz Coffee Company in the Mapo neighbourhood is Seoul\'s most awarded independent roastery. Bakes its own bread, roasts its own coffee, and has become a pilgrimage site for specialty coffee lovers across Asia.',
    address: '28-11 Dowhagak-ro, Mapo-gu, Seoul, South Korea',
    city: 'Seoul', neighborhood: 'Mapo',
    lat: 37.55500, lng: 126.92480,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe8]),
    priceLevel: 2, wifiSpeedMbps: 350, wifiUploadMbps: 300, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    specialtyCoffee: true, roasterName: 'Fritz Coffee Company', foodOptions: 'LIGHT_BITES',
    averageRating: 4.9, reviewCount: 77,
  }),

];

export const sampleCuratedLists: Omit<CuratedListType, 'id' | 'createdAt' | 'items'>[] = [
  {
    title: 'Best Cafes for Coding & Deep Work',
    slug: 'best-cafes-for-coding-and-deep-work',
    description: 'Curated spots with 150+ Mbps fiber, outlets at every desk, and strict noise zones. Perfect for 8-hour engineering sessions.',
    coverImage: IMAGES.cafe2,
    isPublic: true, tags: JSON.stringify(['Coding', 'Fast WiFi', 'Quiet', 'Outlets']),
    authorName: 'Alex Rivera (Lead Nomad Engineer)',
  },
  {
    title: 'Late-Night Think Tanks',
    slug: 'late-night-think-tanks-study-spots',
    description: 'Spots open until 10 PM or later, with solid WiFi, good lighting, and staff that never rushes you.',
    coverImage: IMAGES.cafe1,
    isPublic: true, tags: JSON.stringify(['Open Late', 'Night Owls', 'Students']),
    authorName: 'Sarah Chen (UI/UX Designer)',
  },
  {
    title: 'Specialty Pour-Over & Natural Light',
    slug: 'specialty-pourover-and-natural-light',
    description: 'For coffee purists and designers who need floor-to-ceiling sun, world-class beans, and a calm creative atmosphere.',
    coverImage: IMAGES.cafe3,
    isPublic: true, tags: JSON.stringify(['Specialty Coffee', 'Natural Light', 'Creative']),
    authorName: 'Kenji Sato (Independent Designer)',
  },
  {
    title: 'Top India Nomad Cafes',
    slug: 'top-india-nomad-cafes',
    description: 'The best work-ready cafes across Indian cities — from Mumbai and Bengaluru to Pune, Delhi, and Hyderabad.',
    coverImage: IMAGES.cafe7,
    isPublic: true, tags: JSON.stringify(['India', 'Mumbai', 'Bengaluru', 'Nomads']),
    authorName: 'Priya Sharma (Freelance Developer)',
  },
];
