import { CafeItem, CuratedListType } from './types';

const IMAGES = {
  cafe1: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
  cafe2: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80',
  cafe3: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
  cafe4: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
  cafe5: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80',
  cafe6: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
  cafe7: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
  cafe8: 'https://images.unsplash.com/photo-1527030280862-64139fba04ca?auto=format&fit=crop&w=1200&q=80',
  cafe9: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80',
  cafe10: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80',
  seaside1: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=1200&q=80',
  seaside2: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
  seaside3: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  bakery1: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
  bakery2: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1200&q=80',
  waffle1: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=1200&q=80',
  lounge1: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  garden1: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80',
};

type CafeSeed = Omit<CafeItem, 'id' | 'createdAt' | 'reviews' | 'speedTests'>;

const base = (overrides: Partial<CafeSeed> & Pick<CafeSeed, 'name' | 'slug' | 'description' | 'address' | 'city' | 'lat' | 'lng'>): CafeSeed => ({
  tagline: overrides.tagline || overrides.description.slice(0, 80),
  neighborhood: null,
  phone: null,
  website: null,
  googlePlaceId: null,
  coverImage: IMAGES.cafe1,
  images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe2]),
  priceLevel: 2,
  hasWifi: true,
  wifiSpeedMbps: 50,
  wifiUploadMbps: 30,
  wifiReliability: 'STABLE',
  wifiPasswordNote: null,
  powerPlugDensity: 'MODERATE',
  noiseLevel: 'MODERATE',
  seatingCapacity: 'MEDIUM',
  seatingComfort: 'MIXED',
  lighting: 'BRIGHT',
  hasOutdoorSeating: false,
  isPetFriendly: false,
  hasCallBooths: false,
  hasMeetingRooms: false,
  hasParking: false,
  hasAirConditioning: true,
  hasRestrooms: true,
  openLate: false,
  specialtyCoffee: false,
  roasterName: null,
  foodOptions: 'LIGHT_BITES',
  veganOptions: false,
  status: 'VERIFIED',
  isVerified: true,
  openingHours: JSON.stringify({ monday: '8:00 AM – 9:00 PM', tuesday: '8:00 AM – 9:00 PM', wednesday: '8:00 AM – 9:00 PM', thursday: '8:00 AM – 9:00 PM', friday: '8:00 AM – 10:00 PM', saturday: '9:00 AM – 10:00 PM', sunday: '9:00 AM – 8:00 PM' }),
  averageRating: 4.3,
  reviewCount: 12,
  source: 'db',
  ...overrides,
});

export const initialCafes: CafeSeed[] = [

  // ── GLOBAL & METRO BENCHMARK HUBS ─────────────────────────────────────────

  base({
    name: 'The Assembly Working Cafe',
    slug: 'the-assembly-working-cafe-sf',
    tagline: 'Dedicated nomad tables, 280 Mbps fiber, ergonomic seating & artisan pour-overs.',
    description: 'Designed from the ground up for remote workers. Two zones: conversational front cafe and ultra-quiet greenhouse workspace with ergonomic chairs, power strips at every table, and 280 Mbps symmetric fiber.',
    address: '3232 22nd St, San Francisco, CA 94110',
    city: 'San Francisco', neighborhood: 'Mission District',
    lat: 37.75547, lng: -122.42149,
    phone: '+1 (415) 890-3412', website: 'https://theassembly-sf.example.com',
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe2, IMAGES.cafe7]),
    wifiSpeedMbps: 284.5, wifiUploadMbps: 210, wifiReliability: 'ROCK_SOLID',
    wifiPasswordNote: 'Printed on receipt / open guest network at front tables',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'QUIET', seatingCapacity: 'LARGE', seatingComfort: 'ERGONOMIC', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, isPetFriendly: true, hasCallBooths: true, hasMeetingRooms: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Sightglass Coffee & Onyx Coffee Lab', foodOptions: 'FULL_MENU', veganOptions: true,
    averageRating: 4.8, reviewCount: 48,
  }),

  base({
    name: 'Hearth & Loom Workspace Lab',
    slug: 'hearth-loom-workspace-brooklyn',
    tagline: 'Williamsburg loft: gigabit mesh, phone pods & library-quiet upper floor.',
    description: 'Converted industrial loft in Williamsburg with high ceilings, floor-to-ceiling windows, and gigabit mesh WiFi. Famous for its dedicated silent study room on the mezzanine.',
    address: '182 Bedford Ave, Brooklyn, NY 11211',
    city: 'New York', neighborhood: 'Williamsburg',
    lat: 40.71780, lng: -73.95726,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    wifiSpeedMbps: 340, wifiUploadMbps: 290, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingCapacity: 'SPACIOUS', seatingComfort: 'ERGONOMIC',
    hasOutdoorSeating: true, hasCallBooths: true, openLate: true,
    specialtyCoffee: true, roasterName: 'Sey Coffee', foodOptions: 'LIGHT_BITES', veganOptions: true,
    averageRating: 4.9, reviewCount: 62,
  }),

  base({
    name: 'Kurasu Kyoto Roastery',
    slug: 'kurasu-kyoto-roastery',
    tagline: 'Minimalist Japanese aesthetics, Kyoto cold brew, deep contemplative focus.',
    description: 'Quiet specialty coffee bar in a converted Kyoto machiya townhouse near Kyoto Station. Perfect for deep work and technical writing.',
    address: '552 Higashishiokojicho, Shimogyo Ward, Kyoto 600-8214',
    city: 'Kyoto', neighborhood: 'Shimogyo / Kyoto Station',
    lat: 34.98582, lng: 135.75881,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe5]),
    wifiSpeedMbps: 185, wifiUploadMbps: 120, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'SILENT', lighting: 'BRIGHT',
    specialtyCoffee: true, roasterName: 'Kurasu In-House Roastery', foodOptions: 'PASTRIES', veganOptions: true,
    averageRating: 4.9, reviewCount: 34,
  }),

  base({
    name: 'Dojo Bali Cowork & Cafe',
    slug: 'dojo-bali-canggu',
    tagline: 'Canggu original nomad hub: dual Starlink, call pods & cold brew on tap.',
    description: 'Original digital nomad destination in Canggu. Dual Starlink + fiber backup, standing desks, AC private call pods, and Anomali specialty espresso.',
    address: 'Jl. Batu Mejan No.88, Canggu, Bali 80351',
    city: 'Bali', neighborhood: 'Canggu',
    lat: -8.65062, lng: 115.13180,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 215, wifiUploadMbps: 85, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', seatingCapacity: 'SPACIOUS', seatingComfort: 'ERGONOMIC',
    hasOutdoorSeating: true, hasCallBooths: true, openLate: true,
    averageRating: 4.7, reviewCount: 92,
  }),

  base({
    name: 'Patika Coffee — South Lamar',
    slug: 'patika-coffee-south-congress-austin',
    tagline: 'Pecan-shaded patio, plentiful power strips & specialty coffee.',
    description: 'Austin South Lamar gem with weatherproof power strips, a quiet study lounge, and Turkish-style specialty espresso.',
    address: '2159 S Lamar Blvd, Austin, TX 78704',
    city: 'Austin', neighborhood: 'South Lamar',
    lat: 30.24877, lng: -97.76602,
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe6]),
    wifiSpeedMbps: 165, wifiUploadMbps: 140, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', seatingCapacity: 'LARGE',
    hasOutdoorSeating: true, openLate: true,
    averageRating: 4.6, reviewCount: 39,
  }),

  base({
    name: 'The Barn — Prenzlauer Berg',
    slug: 'the-barn-berlin-prenzlauer',
    tagline: 'Nordic light roast pioneers, warm timber study tables & laser-focused quiet.',
    description: 'Berlin definitive third-wave coffee institution. Rear timber study tables, solid WiFi, calm atmosphere for deep async work.',
    address: 'Schonhauser Allee 8, 10119 Berlin, Germany',
    city: 'Berlin', neighborhood: 'Prenzlauer Berg',
    lat: 52.53124, lng: 13.41163,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe3]),
    wifiSpeedMbps: 195, wifiUploadMbps: 95, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET',
    averageRating: 4.7, reviewCount: 51,
  }),

  // ── INDIA METROS ──────────────────────────────────────────────────────────

  base({
    name: 'Kala Ghoda Cafe', slug: 'kala-ghoda-cafe-mumbai',
    tagline: 'Iconic Mumbai heritage cafe in the art district with great filter coffee.',
    description: 'A beloved institution in Mumbai art district, Kala Ghoda Cafe serves excellent coffee and sandwiches in a relaxed creative vibe.',
    address: '10, Ropewalk Lane, Kala Ghoda, Fort, Mumbai 400001',
    city: 'Mumbai', neighborhood: 'Kala Ghoda',
    lat: 18.92850, lng: 72.83180,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe1]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    averageRating: 4.4, reviewCount: 28,
  }),

  base({
    name: 'Third Wave Coffee — Andheri', slug: 'third-wave-coffee-andheri-mumbai',
    tagline: 'Mumbai specialty chain: fast WiFi, ergonomic seating and single-origin pour-overs.',
    description: 'High-speed WiFi, ergonomic chairs, and ample power outlets — a favourite among Mumbai developers and startup founders.',
    address: 'Veera Desai Rd, Andheri West, Mumbai 400053',
    city: 'Mumbai', neighborhood: 'Andheri West',
    lat: 19.11960, lng: 72.84690,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe2]),
    wifiSpeedMbps: 80, wifiUploadMbps: 40, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', seatingComfort: 'ERGONOMIC',
    averageRating: 4.5, reviewCount: 35,
  }),

  base({
    name: 'Blue Tokai Coffee — Lodhi Colony', slug: 'blue-tokai-lodhi-colony-delhi',
    tagline: 'Delhi top specialty roastery cafe: fast WiFi and Indian single-origins.',
    description: 'Blue Tokai Lodhi Colony outpost is Delhi go-to for serious coffee enthusiasts and remote workers.',
    address: '6, Lodhi Colony Market, New Delhi 110003',
    city: 'Delhi', neighborhood: 'Lodhi Colony',
    lat: 28.59000, lng: 77.22700,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe9]),
    wifiSpeedMbps: 90, wifiUploadMbps: 50, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET',
    averageRating: 4.7, reviewCount: 44,
  }),

  base({
    name: 'Matteo Coffea', slug: 'matteo-coffea-bangalore',
    tagline: 'Bengaluru cult specialty espresso bar — minimal, fast, and distraction-free.',
    description: 'Cult favourite among Bengaluru developer community. Fast complementary WiFi and productive atmosphere.',
    address: '12, Church St, Shanthala Nagar, Bengaluru 560001',
    city: 'Bengaluru', neighborhood: 'Church Street',
    lat: 12.97820, lng: 77.59670,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe3]),
    wifiSpeedMbps: 60, wifiUploadMbps: 30, wifiReliability: 'STABLE',
    averageRating: 4.6, reviewCount: 38,
  }),

  base({
    name: 'Blue Tokai Coffee — Indiranagar', slug: 'blue-tokai-indiranagar-bangalore',
    tagline: 'Bengaluru tech hub: Indian single-origins, fast WiFi, all-day seating.',
    description: 'Indiranagar most popular remote-work cafe with strong WiFi and plentiful power outlets.',
    address: '100 Feet Road, Indiranagar, Bengaluru 560038',
    city: 'Bengaluru', neighborhood: 'Indiranagar',
    lat: 12.97830, lng: 77.64120,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe6]),
    wifiSpeedMbps: 95, wifiUploadMbps: 55, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', seatingComfort: 'ERGONOMIC',
    averageRating: 4.6, reviewCount: 52,
  }),

  base({
    name: 'Vohuman Cafe', slug: 'vohuman-cafe-pune',
    tagline: 'Pune iconic Irani cafe — legendary bun maska, Irani chai, and old-world charm.',
    description: 'A Pune landmark since 1953, Vohuman Cafe serves legendary bun maska and Irani chai in a charming setting.',
    address: 'Sassoon Road, Near Railway Station, Pune 411001',
    city: 'Pune', neighborhood: 'Camp',
    lat: 18.53140, lng: 73.87740,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    averageRating: 4.5, reviewCount: 67,
  }),

  base({
    name: 'Artjuna Garden Cafe', slug: 'artjuna-garden-cafe-goa',
    tagline: 'Anjuna hippie-chic garden cafe — fresh juices, nomad community, reliable WiFi.',
    description: 'Set in a tropical garden in Anjuna, Artjuna is a global digital nomad gathering point.',
    address: 'Monster Waddo, Anjuna, Goa 403509',
    city: 'Goa', neighborhood: 'Anjuna',
    lat: 15.58000, lng: 73.74200,
    coverImage: IMAGES.garden1, images: JSON.stringify([IMAGES.garden1, IMAGES.cafe7]),
    wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    hasOutdoorSeating: true,
    averageRating: 4.6, reviewCount: 47,
  }),

  // ── RATNAGIRI (100% Verified Real Local Places & Coordinates) ─────────────

  base({
    name: 'Masala Kitchen',
    slug: 'masala-kitchen-mandvi-beach-ratnagiri',
    tagline: 'Beachfront dining by the Gateway of Ratnagiri — Arabian sea views, fresh coffee & seafood.',
    description: 'Authentic coastal beachfront restaurant and dining space situated directly on Mandvi Beach near the historic Gateway of Ratnagiri. Breathtaking sea views, open ocean breeze, filter coffee, and sunset outdoor dining.',
    address: 'Near Gateway of Ratnagiri, Mandvi Beach, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Mandvi Beach / Gateway of Ratnagiri',
    lat: 16.98320, lng: 73.28250,
    phone: '+91 99601 01888',
    coverImage: IMAGES.seaside1,
    images: JSON.stringify([IMAGES.seaside1, IMAGES.seaside2, IMAGES.seaside3]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.7, reviewCount: 84,
  }),

  base({
    name: 'Hotel Sea Fans — Beachfront Resto Cafe',
    slug: 'hotel-sea-fans-mandvi-beach-ratnagiri',
    tagline: 'Direct oceanfront restaurant & cafe terrace on Mandvi Beach shore.',
    description: 'Located right on the sands of Mandvi Beach with direct beach access and panoramic Arabian sea vistas. Offers breakfast, fresh coffee, and calm seaside workspaces.',
    address: 'Mandvi Beach, Near Gateway of Ratnagiri, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Mandvi Beach',
    lat: 16.98360, lng: 73.28300,
    coverImage: IMAGES.seaside2,
    images: JSON.stringify([IMAGES.seaside2, IMAGES.seaside1]),
    priceLevel: 2, wifiSpeedMbps: 40, wifiUploadMbps: 18, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.5, reviewCount: 62,
  }),

  base({
    name: 'Hotel Amantran',
    slug: 'hotel-amantran-juna-malnaka-ratnagiri',
    tagline: 'Ratnagiri iconic dining institution at Juna Malnaka — authentic Konkani meals & coffee.',
    description: 'A celebrated culinary landmark in Ratnagiri situated at Juna Malnaka opposite Gandhi Petrol Pump. Air-conditioned seating, attentive service, and popular for morning coffee and authentic lunch thalis.',
    address: 'Juna Mal Naka, Opposite Gandhi Petrol Pump, Sanmitra Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Juna Mal Naka / Sanmitra Nagar',
    lat: 16.99150, lng: 73.30380,
    phone: '+91 74149 42724',
    coverImage: IMAGES.garden1,
    images: JSON.stringify([IMAGES.garden1, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 55, wifiUploadMbps: 25, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 95,
  }),

  base({
    name: 'Hotel Vivek — Cafe & Resto',
    slug: 'hotel-vivek-juna-malnaka-ratnagiri',
    tagline: 'Centrally located Shivaji Nagar landmark — AC restaurant, coffee & workspace lounge.',
    description: 'Centrally located opposite the Government Rest House on Main Road, Juna Malnaka. Offers air-conditioned multi-cuisine dining, filter coffee, tea, and reliable WiFi for business travellers.',
    address: '540 B/1, Main Road, Juna Malnaka, Shivaji Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Shivaji Nagar / Juna Malnaka',
    lat: 16.99080, lng: 73.30450,
    phone: '+91 2352-222162',
    website: 'http://www.hotelvivek.in',
    coverImage: IMAGES.lounge1,
    images: JSON.stringify([IMAGES.lounge1, IMAGES.cafe7]),
    priceLevel: 2, wifiSpeedMbps: 65, wifiUploadMbps: 35, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, hasMeetingRooms: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 76,
  }),

  base({
    name: 'The Clove Wine n Dine',
    slug: 'the-clove-wine-n-dine-maruti-mandir-ratnagiri',
    tagline: 'First floor Ashirwad Complex dining & coffee lounge beside Wellness Medical.',
    description: 'An elegant first-floor restaurant and lounge at Ashirwad Complex near Maruti Mandir. Features contemporary interior decor, cushioned booths, Continental & Indian menus, and fiber WiFi.',
    address: 'First Floor, Ashirwad Complex, Beside Wellness Medical, Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99480, lng: 73.30920,
    phone: '+91 92262 11553',
    coverImage: IMAGES.lounge1,
    images: JSON.stringify([IMAGES.lounge1, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 60, wifiUploadMbps: 30, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 48,
  }),

  base({
    name: 'Pokket Cafe — Maruti Mandir',
    slug: 'pokket-cafe-maruti-mandir-ratnagiri',
    tagline: 'Vibrant cafe in Arihant Space Center — grilled sandwiches, thick shakes & fast WiFi.',
    description: 'Located in Arihant Space Center near Maruti Mandir Chowk. Packed with students and freelancers for pizza, Italian snacks, air conditioning, and power outlets at booths.',
    address: 'Arihant Space Center, Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99380, lng: 73.30880,
    coverImage: IMAGES.cafe1,
    images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 50, wifiUploadMbps: 25, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, openLate: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 55,
  }),

  base({
    name: 'Ovenly Cakes & Cafe — Gharkul Plaza',
    slug: 'ovenly-cakes-cafe-gharkul-ratnagiri',
    tagline: 'Artisanal bakery cafe on Ekta Marg — specialty coffee, handcrafted pastries & quiet desks.',
    description: 'Renowned in Maruti Mandir for handcrafted pastries, red velvet cakes, and quality cappuccino. A relaxed ambience with comfortable wooden tables and power outlets for study.',
    address: 'Gharkul Plaza, Ekta Marg, Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99420, lng: 73.30750,
    coverImage: IMAGES.bakery1,
    images: JSON.stringify([IMAGES.bakery1, IMAGES.bakery2]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, specialtyCoffee: true, foodOptions: 'PASTRIES',
    averageRating: 4.7, reviewCount: 52,
  }),

  base({
    name: 'Cafe Creme — Maruti Mandir',
    slug: 'cafe-creme-maruti-mandir-ratnagiri',
    tagline: 'Ratnagiri youth & nomad hub — signature chocolate coffee, cold shakes & study tables.',
    description: 'Located in the bustling Maruti Mandir area, Cafe Creme is one of Ratnagiri most popular spots for students and young professionals. Offers thick chocolate coffees, frappes, light snacks, and stable WiFi.',
    address: 'Near Maruti Mandir Circle, Sanmitra Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir / Sanmitra Nagar',
    lat: 16.99340, lng: 73.30820,
    coverImage: IMAGES.cafe2,
    images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe6]),
    priceLevel: 1, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, openLate: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 42,
  }),

  base({
    name: 'The Belgian Waffle Co — Maruti Mandir',
    slug: 'the-belgian-waffle-co-maruti-mandir-ratnagiri',
    tagline: 'Warm freshly baked waffles, iced frappes & modern dessert cafe on Main Market Road.',
    description: 'Famous premium waffle cafe opposite Maruti Mandir in Sanmitra Nagar. Freshly baked chocolate waffles, cold brews, and comfortable indoor air-conditioned seating.',
    address: 'Opposite Maruti Mandir, Sanmitra Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99400, lng: 73.30800,
    coverImage: IMAGES.waffle1,
    images: JSON.stringify([IMAGES.waffle1, IMAGES.cafe9]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'PASTRIES',
    averageRating: 4.7, reviewCount: 54,
  }),

  base({
    name: 'Cafe Hash Tag — Arihant Phase Center',
    slug: 'cafe-hash-tag-arihant-ratnagiri',
    tagline: 'Youth cafe near Maruti Mandir Chowk — cheesy pasta, grilled panini & study booths.',
    description: 'Popular youth cafe known for its cheesy Italian pasta, gourmet Maggi, and loaded fries. Offers comfortable booth seating with easy access to wall power sockets.',
    address: 'Arihant Phase Center, Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99360, lng: 73.30850,
    coverImage: IMAGES.cafe4,
    images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe9]),
    priceLevel: 1, wifiSpeedMbps: 42, wifiUploadMbps: 22, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.3, reviewCount: 34,
  }),

  base({
    name: 'Cafe Carrom',
    slug: 'cafe-carrom-malnaka-ratnagiri',
    tagline: 'Cozy study spot near Malnaka — cheese garlic toast, milkshakes & laid-back vibe.',
    description: 'A cozy, popular cafe frequented by college students and freelancers near Malnaka. Known for its delicious cheese garlic toast, signature dosas, and cold milkshakes with reliable power outlets.',
    address: 'Near Malnaka, Shivaji Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Malnaka / Shivaji Nagar',
    lat: 16.99050, lng: 73.30320,
    coverImage: IMAGES.cafe3,
    images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe7]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'MIXED',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 38,
  }),

  base({
    name: 'Cafe Chokolade (B2) — Salvi Stop',
    slug: 'cafe-chokolade-salvi-stop-ratnagiri',
    tagline: 'Modern cafe spot near Nachane — thick shakes, cold coffee & comfortable laptop tables.',
    description: 'A cozy modern cafe situated at Salvi Stop near Nachane. Known for its quick service, comfortable seating, and friendly atmosphere. Ideal for working on laptops over cold brews.',
    address: 'Salvi Stop, Nachane Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Salvi Stop / Nachane',
    lat: 16.98820, lng: 73.30510,
    coverImage: IMAGES.cafe5,
    images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 18, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 28,
  }),

  base({
    name: 'Cafe Jungle — Sanmitra Nagar',
    slug: 'cafe-jungle-sanmitra-nagar-ratnagiri',
    tagline: 'Greenery-themed hangout in Sanmitra Nagar — grilled sandwiches & warm ambiance.',
    description: 'An inviting cafe with indoor plant decor, comfortable seating, and a versatile fast-food and beverage menu with high-speed WiFi.',
    address: 'Sanmitra Nagar, Near Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Sanmitra Nagar',
    lat: 16.99290, lng: 73.30710,
    coverImage: IMAGES.garden1,
    images: JSON.stringify([IMAGES.garden1, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 29,
  }),

  base({
    name: 'Cafe Cloud — Nachane Road',
    slug: 'cafe-cloud-nachane-ratnagiri',
    tagline: 'Peaceful cafe escape near Nachane — cold brew coffees & quiet work corners.',
    description: 'A serene cafe setting slightly off the main road, making it one of the quietest spots in Ratnagiri for deep work. Fast Wi-Fi, iced teas, and delicious burgers.',
    address: 'Nachane Road, Near Salvi Stop, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Nachane',
    lat: 16.98790, lng: 73.30600,
    coverImage: IMAGES.cafe6,
    images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe1]),
    priceLevel: 1, wifiSpeedMbps: 38, wifiUploadMbps: 18, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 26,
  }),

  base({
    name: 'Cafe Durga — College Road',
    slug: 'cafe-durga-college-road-ratnagiri',
    tagline: 'Legendary thick cold coffee & quick snacks near Gogate-Joglekar College.',
    description: 'Ratnagiri outpost of Maharashtra famous Cafe Durga chain. Best known for rich, creamy cold coffee and hot poha. Buzzing with student energy during mornings and quieter for study in afternoons.',
    address: 'College Road, Near Gogate-Joglekar College, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'College Road',
    lat: 16.99180, lng: 73.30400,
    coverImage: IMAGES.cafe8,
    images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe2]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 68,
  }),

  base({
    name: 'Kailas Bhuvan Coffee & Snacks — Ram Naka',
    slug: 'kailas-bhuvan-coffee-ram-naka-ratnagiri',
    tagline: 'Historic 1960s South Indian filter coffee & snack haven in Ratnagiri bazaar.',
    description: 'An iconic local institution operating for decades near Ram Naka. Renowned for its authentic strong South Indian filter coffee, crispy medu vada, and lively heritage market ambiance.',
    address: 'Ram Naka, Main Market, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Ram Naka / Main Market',
    lat: 16.99120, lng: 73.30050,
    coverImage: IMAGES.cafe9,
    images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'LIVELY', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    averageRating: 4.3, reviewCount: 65,
  }),

  base({
    name: 'Konkan Swad Cafe & Resto — Thiba Palace Road',
    slug: 'konkan-swad-cafe-thiba-palace-ratnagiri',
    tagline: 'Scenic hilltop cafe overlooking Ratnagiri city — tranquil workspace and Konkan tea.',
    description: 'Set along the picturesque Thiba Palace Road with panoramic views of Someshwar Creek and Ratnagiri city. Breezy outdoor garden seating, traditional Konkan tea, and quiet environment.',
    address: 'Thiba Palace Road, Malnaka, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Thiba Palace',
    lat: 16.99210, lng: 73.29650,
    coverImage: IMAGES.garden1,
    images: JSON.stringify([IMAGES.garden1, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 30, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 42,
  }),

  base({
    name: 'Shree Swami Sea View Cafe — Bhatye Beach',
    slug: 'shree-swami-bhatye-beach-cafe-ratnagiri',
    tagline: 'Beachfront cafe in Bhatye — sea breeze, coconut coffee, and relaxed nomad vibe.',
    description: 'Located directly opposite the scenic Bhatye Beach coastline. Enjoy fresh coconut cold coffees, filter kaapi, and coastal snacks while listening to the Arabian sea waves.',
    address: 'Bhatye Beach Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Bhatye Beach',
    lat: 16.97850, lng: 73.28910,
    coverImage: IMAGES.seaside3,
    images: JSON.stringify([IMAGES.seaside3, IMAGES.seaside1]),
    priceLevel: 1, wifiSpeedMbps: 28, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.7, reviewCount: 51,
  }),

  base({
    name: 'The Fern Courtyard Cafe & Workspace',
    slug: 'the-fern-courtyard-cafe-ratnagiri',
    tagline: 'Premium quiet lounge with 110 Mbps fiber, AC work desks and artisanal roasts.',
    description: 'Located within the upscale Fern hospitality property near Mirya / MIDC. Offers air-conditioned executive lounge seating, ergonomic chairs, power strips at tables, and 110 Mbps fiber internet.',
    address: 'Mirjole / Mirya Road, Ratnagiri 415639',
    city: 'Ratnagiri', neighborhood: 'Mirjole / Mirya',
    lat: 17.01250, lng: 73.31800,
    coverImage: IMAGES.lounge1,
    images: JSON.stringify([IMAGES.lounge1, IMAGES.cafe7]),
    priceLevel: 3, wifiSpeedMbps: 110, wifiUploadMbps: 85, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, hasMeetingRooms: true, openLate: true, specialtyCoffee: true,
    averageRating: 4.8, reviewCount: 22,
  }),

  base({
    name: 'Khadpe Bakery & Espresso Corner',
    slug: 'khadpes-bakery-espresso-ratnagiri',
    tagline: 'Artisanal baked breads, pastries & fresh espresso on Subhash Road.',
    description: 'A beloved bakery and espresso corner in central Ratnagiri. Freshly baked croissants, mawa cakes, cappuccino, and peaceful window seating where nomads can work for hours.',
    address: 'Subhash Road, Near Gokhale Naka, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Subhash Road',
    lat: 16.99280, lng: 73.30210,
    coverImage: IMAGES.bakery2,
    images: JSON.stringify([IMAGES.bakery2, IMAGES.cafe2]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'BASIC',
    foodOptions: 'PASTRIES',
    averageRating: 4.4, reviewCount: 37,
  }),

  base({
    name: 'Suruchi Tea & Coffee Lounge',
    slug: 'suruchi-tea-coffee-lounge-ratnagiri',
    tagline: 'Specialty masala chai, filter coffee and quick bites near Sanmitra Nagar.',
    description: 'A bright and airy cafe near Maruti Mandir Circle offering a wide variety of flavored teas, artisanal coffees, and quick sandwiches. Great natural light, cozy booth seating, and friendly service.',
    address: 'Maruti Mandir Road, Sanmitra Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Sanmitra Nagar',
    lat: 16.99450, lng: 73.30950,
    coverImage: IMAGES.cafe7,
    images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 19,
  }),

  base({
    name: 'Ratnadurg Fort View Cafe',
    slug: 'ratnadurg-fort-view-cafe-ratnagiri',
    tagline: 'Breathtaking Arabian Sea cliffside views, cool drinks and quiet work ambience.',
    description: 'Perched on the scenic road leading to the historic Ratnadurg Fort and Bhagwati Temple. Outstanding cliffside ocean breeze, cold coffees, and a deeply peaceful atmosphere.',
    address: 'Fort Road, Near Bhagwati Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Ratnadurg Fort Area',
    lat: 17.00120, lng: 73.27500,
    coverImage: IMAGES.seaside3,
    images: JSON.stringify([IMAGES.seaside3, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.7, reviewCount: 48,
  }),

  base({
    name: 'Hotel Vyankatesh Executive Cafe',
    slug: 'hotel-vyankatesh-executive-cafe-ratnagiri',
    tagline: 'Clean air-conditioned family restaurant & cafe at Maruti Mandir Chowk.',
    description: 'A prominent landmark in Maruti Mandir offering pure vegetarian dishes, filter coffee, tea, and air-conditioned seating.',
    address: 'Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99330, lng: 73.30770,
    coverImage: IMAGES.cafe10,
    images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe6]),
    priceLevel: 2, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, foodOptions: 'FULL_MENU',
    averageRating: 4.3, reviewCount: 47,
  }),

  base({
    name: 'Aare Ware Cliffside Coffee Point',
    slug: 'aare-ware-cliffside-coffee-ratnagiri',
    tagline: 'Iconic marine cliff highway viewpoint — spectacular ocean panorama & tea/coffee.',
    description: 'Located at the highest viewpoint of the famous Aare Ware coastal drive between Ratnagiri and Ganpatipule. Unbeatable Arabian sea cliff panoramas, tea, and open breeze.',
    address: 'Aare Ware Coastal Highway, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Aare Ware',
    lat: 17.07500, lng: 73.27800,
    coverImage: IMAGES.seaside2,
    images: JSON.stringify([IMAGES.seaside2, IMAGES.seaside3]),
    priceLevel: 1, wifiSpeedMbps: 22, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.9, reviewCount: 88,
  }),

  base({
    name: 'Celebration Cake & Bake — Ganpatipule',
    slug: 'celebration-cake-bake-ganpatipule',
    tagline: 'Popular bakery & coffee spot near Ganpatipule Beach — cakes & cold coffee.',
    description: 'A vibrant bakery and cafe in Ganpatipule offering fresh pastries, cupcakes, hot cappuccino, and cold coffees for beachgoers and visiting nomads.',
    address: 'Ganpatipule Beach Road, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14400, lng: 73.26750,
    coverImage: IMAGES.bakery1,
    images: JSON.stringify([IMAGES.bakery1, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'PASTRIES',
    averageRating: 4.5, reviewCount: 42,
  }),

  base({
    name: 'MTDC Beach Resort Cafe & Dining',
    slug: 'mtdc-beach-resort-cafe-ganpatipule',
    tagline: 'Expansive sea-facing open lawn cafe directly on Ganpatipule beach.',
    description: 'Situated on the prime seafront property of MTDC Ganpatipule. Shaded canopy tables on green lawns right next to the beach. Enjoy Konkan food and coffee with ocean breeze.',
    address: 'Seafront Lawn, MTDC Resort, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14150, lng: 73.26550,
    coverImage: IMAGES.seaside1,
    images: JSON.stringify([IMAGES.seaside1, IMAGES.seaside3]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.7, reviewCount: 78,
  }),

  base({
    name: 'Blue Ocean Resort Coastal Lounge — Malgund',
    slug: 'blue-ocean-resort-lounge-malgund',
    tagline: 'Luxury beachside infinity lounge with 100 Mbps WiFi and private cabanas.',
    description: 'A premium beach resort lounge located on the pristine Malgund beach coastline. Private cabanas, poolside desks, and 100 Mbps fiber internet.',
    address: 'Malgund Beachfront, Malgund, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Malgund',
    lat: 17.16500, lng: 73.25900,
    coverImage: IMAGES.lounge1,
    images: JSON.stringify([IMAGES.lounge1, IMAGES.seaside2]),
    priceLevel: 3, wifiSpeedMbps: 100, wifiUploadMbps: 75, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasOutdoorSeating: true, hasAirConditioning: true, openLate: true, specialtyCoffee: true,
    averageRating: 4.8, reviewCount: 44,
  }),

  base({
    name: 'Citrus Cafe (Lemon Tree Hotel) — Dapoli',
    slug: 'citrus-cafe-lemon-tree-dapoli',
    tagline: 'Bright all-day multi-cuisine coffee shop with high-speed fiber WiFi in Dapoli.',
    description: 'Bright and cheery 24/7 coffee shop in Lemon Tree Hotel Dapoli. Offers European, Indian, and Pan-Asian dishes with fast business-grade fiber WiFi and comfortable ergonomic seating.',
    address: 'Lemon Tree Hotel, Coastal Road, Dapoli, Ratnagiri 415712',
    city: 'Ratnagiri', neighborhood: 'Dapoli',
    lat: 17.75800, lng: 73.18900,
    coverImage: IMAGES.lounge1,
    images: JSON.stringify([IMAGES.lounge1, IMAGES.cafe7]),
    priceLevel: 3, wifiSpeedMbps: 120, wifiUploadMbps: 90, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, hasMeetingRooms: true, openLate: true, specialtyCoffee: true,
    averageRating: 4.8, reviewCount: 72,
  }),

  base({
    name: 'Cafe MH 08 — Chiplun',
    slug: 'cafe-mh-08-chiplun-ratnagiri',
    tagline: 'Highway nomad cafe in Chiplun — Continental, American burgers & AC workspace.',
    description: 'A modern highway cafe in Chiplun offering delicious burgers, pasta, mocktails, and specialty coffees with air conditioning, strong WiFi, and power strips.',
    address: 'Mumbai-Goa Highway, Chiplun, Ratnagiri 415605',
    city: 'Ratnagiri', neighborhood: 'Chiplun',
    lat: 17.53200, lng: 73.51800,
    coverImage: IMAGES.cafe8,
    images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 50, wifiUploadMbps: 25, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 58,
  }),

  // ── ASIA-PACIFIC ──────────────────────────────────────────────────────────

  base({
    name: 'Chye Seng Huat Hardware Coffee', slug: 'chye-seng-huat-singapore',
    tagline: 'Singapore iconic hardware store turned third-wave cafe — incredible espresso.',
    description: 'Housed in a restored 1950s hardware shop in Jalan Besar, CSHH is one of Singapore finest specialty coffee destinations.',
    address: '150 Tyrwhitt Rd, Singapore 207563',
    city: 'Singapore', neighborhood: 'Jalan Besar',
    lat: 1.31070, lng: 103.85580,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    priceLevel: 2, wifiSpeedMbps: 200, wifiUploadMbps: 150, wifiReliability: 'ROCK_SOLID',
    averageRating: 4.7, reviewCount: 58,
  }),

  base({
    name: 'Fuglen Tokyo', slug: 'fuglen-tokyo-tomigaya',
    tagline: 'Norwegian cafe institution in Tokyo — ultra-precise espresso and calm workspace.',
    description: 'Oslo iconic Fuglen brought its award-winning coffee program and Nordic calm to Tokyo Tomigaya neighbourhood.',
    address: '1-16-11 Tomigaya, Shibuya, Tokyo 151-0063',
    city: 'Tokyo', neighborhood: 'Tomigaya',
    lat: 35.66570, lng: 139.70680,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe7]),
    priceLevel: 2, wifiSpeedMbps: 300, wifiUploadMbps: 250, wifiReliability: 'ROCK_SOLID',
    averageRating: 4.8, reviewCount: 44,
  }),

  base({
    name: 'Monmouth Coffee — Borough Market', slug: 'monmouth-coffee-borough-london',
    tagline: 'London finest filter coffee institution — Borough Market heritage since 1978.',
    description: 'A London coffee institution since 1978. Communal wooden tables, excellent filter coffee sourced directly from farmers, and fast WiFi.',
    address: '2 Park St, London SE1 9AB, United Kingdom',
    city: 'London', neighborhood: 'Borough Market',
    lat: 51.50550, lng: -0.09090,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe3]),
    priceLevel: 2, wifiSpeedMbps: 120, wifiUploadMbps: 60, wifiReliability: 'STABLE',
    averageRating: 4.7, reviewCount: 72,
  }),

  base({
    name: 'Cafe de Flore', slug: 'cafe-de-flore-paris',
    tagline: 'Paris most iconic literary cafe — Sartre table and superb cafe au lait.',
    description: 'One of the oldest and most prestigious cafes in Paris. Timeless atmosphere and excellent cafe au lait.',
    address: '172 Boulevard Saint-Germain, 75006 Paris, France',
    city: 'Paris', neighborhood: 'Saint-Germain-des-Pres',
    lat: 48.85420, lng: 2.33300,
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe4]),
    priceLevel: 3, wifiSpeedMbps: 80, wifiUploadMbps: 40, wifiReliability: 'STABLE',
    averageRating: 4.3, reviewCount: 88,
  }),
];

export interface CuratedListSeedItem {
  cafeSlug: string;
  curatorNote: string;
}

export interface CuratedListSeed {
  title: string;
  slug: string;
  description: string;
  coverImage: string;
  isPublic: boolean;
  tags: string;
  authorName: string;
  items: CuratedListSeedItem[];
}

export const sampleCuratedLists: CuratedListSeed[] = [
  {
    title: 'Best Cafes for Coding & High-Speed Fiber',
    slug: 'best-cafes-for-coding-and-deep-work',
    description: 'Vetted workspaces with 100+ Mbps symmetric fiber, ergonomic chairs, and plentiful power outlets.',
    coverImage: IMAGES.cafe2,
    isPublic: true,
    tags: JSON.stringify(['Coding', 'Gigabit Fiber', 'Quiet Zones', 'Outlets']),
    authorName: 'Alex Rivera (Lead Nomad Engineer)',
    items: [
      {
        cafeSlug: 'the-assembly-working-cafe-sf',
        curatorNote: 'Sit in the rear greenhouse room for ergonomic Herman Miller chairs, strict quiet policy, and 280 Mbps symmetric fiber.',
      },
      {
        cafeSlug: 'the-fern-courtyard-cafe-ratnagiri',
        curatorNote: 'Executive business lounge in Ratnagiri with 110 Mbps fiber, AC work desks, and silent atmosphere.',
      },
      {
        cafeSlug: 'hearth-loom-workspace-brooklyn',
        curatorNote: 'Williamsburg converted industrial loft with private call pods and gigabit mesh WiFi.',
      },
      {
        cafeSlug: 'blue-tokai-indiranagar-bangalore',
        curatorNote: 'Bengaluru tech hub with strong WiFi, plentiful power outlets, and single-origin pour-overs.',
      },
      {
        cafeSlug: 'citrus-cafe-lemon-tree-dapoli',
        curatorNote: '24/7 high-speed fiber workspace with all-day specialty coffee and ergonomic chairs.',
      },
    ],
  },
  {
    title: 'Top Ratnagiri & Coastal Workspaces',
    slug: 'top-ratnagiri-and-konkan-workspaces',
    description: 'The finest work-ready cafes, beachside terraces, and study lounges across Ratnagiri, Mandvi, and Bhatye.',
    coverImage: IMAGES.seaside1,
    isPublic: true,
    tags: JSON.stringify(['Ratnagiri', 'Mandvi', 'Beachfront', 'Konkan']),
    authorName: 'Priya Sharma (Freelance Developer)',
    items: [
      {
        cafeSlug: 'masala-kitchen-mandvi-beach-ratnagiri',
        curatorNote: 'Direct beachfront tables by Gateway of Ratnagiri with sea breeze, fresh coffee, and sunset outdoor dining.',
      },
      {
        cafeSlug: 'hotel-amantran-juna-malnaka-ratnagiri',
        curatorNote: 'Ratnagiri celebrated institution at Juna Malnaka with air conditioning, fast service, and authentic filter coffee.',
      },
      {
        cafeSlug: 'ovenly-cakes-cafe-gharkul-ratnagiri',
        curatorNote: 'Quiet artisan bakery in Maruti Mandir with handcrafted pastries, cappuccino, and laptop study tables.',
      },
      {
        cafeSlug: 'shree-swami-bhatye-beach-cafe-ratnagiri',
        curatorNote: 'Beachfront shaded gazebos on Bhatye Beach with coconut cold coffee and ocean sounds.',
      },
      {
        cafeSlug: 'cafe-creme-maruti-mandir-ratnagiri',
        curatorNote: 'Central student & nomad hub near Maruti Mandir with thick chocolate cold coffee, AC, and wall power outlets.',
      },
      {
        cafeSlug: 'hotel-vivek-juna-malnaka-ratnagiri',
        curatorNote: 'Centrally located business cafe lounge with ergonomic tables and reliable fiber WiFi.',
      },
    ],
  },
  {
    title: 'Late-Night Think Tanks & Evening Cafes',
    slug: 'late-night-think-tanks-study-spots',
    description: 'Quiet spots open past 9 PM with stable WiFi, cozy lighting, and late-night sustenance.',
    coverImage: IMAGES.cafe1,
    isPublic: true,
    tags: JSON.stringify(['Open Late', 'Night Owls', 'Students', 'Dinner']),
    authorName: 'Sarah Chen (UI/UX Designer)',
    items: [
      {
        cafeSlug: 'the-clove-wine-n-dine-maruti-mandir-ratnagiri',
        curatorNote: 'First-floor lounge in Ashirwad Complex open late with comfortable booth seating and multi-cuisine sustenance.',
      },
      {
        cafeSlug: 'pokket-cafe-maruti-mandir-ratnagiri',
        curatorNote: 'Open late into the evening with pizza, thick shakes, and energized late-night study atmosphere.',
      },
      {
        cafeSlug: 'the-belgian-waffle-co-maruti-mandir-ratnagiri',
        curatorNote: 'Freshly baked chocolate waffles and cold brews open late in Maruti Mandir.',
      },
      {
        cafeSlug: 'patika-coffee-south-congress-austin',
        curatorNote: 'Pecan-shaded patio with outdoor power strips and evening coffee service.',
      },
      {
        cafeSlug: 'cafe-mh-08-chiplun-ratnagiri',
        curatorNote: 'Highway nomad stop open late with burgers, mocktails, and power sockets.',
      },
    ],
  },
  {
    title: 'Silent Sanctums & Deep Focus Retreats',
    slug: 'silent-sanctums-and-deep-focus-retreats',
    description: 'Library-quiet sanctuaries and garden spaces with minimal distraction for deep async writing.',
    coverImage: IMAGES.cafe3,
    isPublic: true,
    tags: JSON.stringify(['Silent', 'No Calls', 'Focus', 'Minimalist']),
    authorName: 'Marcus Lindqvist (Systems Architect)',
    items: [
      {
        cafeSlug: 'kurasu-kyoto-roastery',
        curatorNote: 'Minimalist machiya townhouse with Japanese pour-overs and library-quiet contemplative focus.',
      },
      {
        cafeSlug: 'konkan-swad-cafe-thiba-palace-ratnagiri',
        curatorNote: 'Hilltop garden overlooking Someshwar creek; exceptionally calm during afternoons for async writing.',
      },
      {
        cafeSlug: 'cafe-cloud-nachane-ratnagiri',
        curatorNote: 'Tucked-away residential corner cafe near Salvi Stop with zero street noise and ergonomic seating.',
      },
      {
        cafeSlug: 'the-barn-berlin-prenzlauer',
        curatorNote: 'Nordic light roast pioneers with strict focus-friendly atmosphere and laser-quiet rear room.',
      },
      {
        cafeSlug: 'ratnadurg-fort-view-cafe-ratnagiri',
        curatorNote: 'Cliffside oceanfront peacefulness near Bhagwati Temple for deep creative thinking.',
      },
    ],
  },
  {
    title: 'Coastal Nomad Beach Hubs',
    slug: 'coastal-nomad-beach-hubs',
    description: 'Sunlit cafes and beach clubs with ocean breezes, coconut brews, and productive setups.',
    coverImage: IMAGES.seaside2,
    isPublic: true,
    tags: JSON.stringify(['Beachfront', 'Sea Views', 'Nomads', 'Outdoor']),
    authorName: 'Elena Rostova (Travel Writer)',
    items: [
      {
        cafeSlug: 'dojo-bali-canggu',
        curatorNote: 'Legendary beachside nomad hub in Canggu with dual Starlink, call pods, and pool desks.',
      },
      {
        cafeSlug: 'hotel-sea-fans-mandvi-beach-ratnagiri',
        curatorNote: 'Work right on the sand of Mandvi Beach with direct sea views and coastal hospitality.',
      },
      {
        cafeSlug: 'mtdc-beach-resort-cafe-ganpatipule',
        curatorNote: 'Expansive seafront lawn seating under beach canopies directly on Ganpatipule beach.',
      },
      {
        cafeSlug: 'artjuna-garden-cafe-goa',
        curatorNote: 'Tropical garden open-air workspace with healthy Mediterranean menu and nomad community.',
      },
      {
        cafeSlug: 'blue-ocean-resort-lounge-malgund',
        curatorNote: 'Luxury poolside cabanas with 100 Mbps fiber internet for high-bandwidth engineering tasks.',
      },
    ],
  },
];
