import sys
import os
import cv2
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QThread, pyqtSignal
from PyQt5.QtGui import QImage, QPixmap
import time
import subprocess
import pyttsx3
import speech_recognition as sr
import random
import webbrowser
import datetime
from datetime import datetime
from plyer import notification
import pyautogui
import wikipedia
import pywhatkit as pwkx
from google import genai
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import requests
from PIL import Image
import io
import base64
import textwrap
import queue as _queue_mod
import nltk
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet', quiet=True)
from nltk.corpus import wordnet
from deep_translator import GoogleTranslator

# Gemini AI Configuration — key is loaded from .env (never hardcoded)
from dotenv import load_dotenv
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise EnvironmentError(
        "GEMINI_API_KEY not found. "
        "Create a .env file in the project folder with:\n"
        "  GEMINI_API_KEY=your_key_here"
    )
genai_client = genai.Client(api_key=GEMINI_API_KEY)
GEMINI_MODEL = "gemini-3.6-flash"

# Thread-safe queue: GUI text input pushes here; command() drains it first.
_text_queue: "_queue_mod.Queue[str]" = _queue_mod.Queue()

def generate_ppt():
    """Generate a PowerPoint presentation from voice input."""
    speak("Please say the topic for your PowerPoint presentation.")
    topic = command()
    
    if not topic:
        speak("No topic detected. Please try again.")
        return

    speak(f"Generating a presentation on {topic}. Please wait.")
    
    try:
        # Generate content using Gemini AI
        prompt = f"Create an educational PowerPoint outline on {topic}. Include a title slide and 4-5 key slides with summarized points."
        response = genai_client.models.generate_content(model=GEMINI_MODEL, contents=prompt)
        slides_content = response.text.split("\n\n")  # Split text into slides

        # Create PowerPoint
        ppt = Presentation()

        # Title Slide
        slide_layout = ppt.slide_layouts[0]
        slide = ppt.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"{topic}"
        subtitle.text = "Generated by Jarvis AI"

        # Add Content Slides
        for slide_text in slides_content:
            slide_layout = ppt.slide_layouts[1]  # Title & Content Layout
            slide = ppt.slides.add_slide(slide_layout)
            title, content = slide.shapes.title, slide.placeholders[1]

            slide_parts = slide_text.split(": ", 1)
            if len(slide_parts) == 2:
                title.text, content.text = slide_parts
            else:
                title.text, content.text = topic, slide_text

        # Save the presentation
        ppt_filename = f"{topic.replace(' ', '_')}.pptx"
        ppt.save(ppt_filename)

        speak(f"Presentation on {topic} has been created successfully. Opening the file now.")
        os.startfile(ppt_filename)

    except Exception as e:
        speak("I encountered an error while generating the presentation.")
        print("Error:", e)

# Initialize text-to-speech engine
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)
engine.setProperty('rate', 180)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

def load_history():
    try:
        with open("conversation_history.txt", "r") as file:
            return file.read()
    except FileNotFoundError:
        return ""

def save_history(user_input, ai_response):
    with open("conversation_history.txt", "a") as file:
        file.write(f"User: {user_input}\nAI: {ai_response}\n\n")

def clear_history():
    open("conversation_history.txt", "w").close()
    speak("Conversation history has been cleared.")

def command():
    # ── Text input takes priority ─────────────────────────────────────────
    try:
        typed = _text_queue.get_nowait()
        print(f"[TEXT] You typed: {typed}")
        return typed.lower()
    except _queue_mod.Empty:
        pass

    # ── Fall through to voice recognition ─────────────────────────────────
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        r.pause_threshold = 1       # better sentence completion
        r.energy_threshold = 300    # detect softer speech
        r.adjust_for_ambient_noise(source, duration=0.5)
        audio = r.listen(source)
    try:
        content = r.recognize_google(audio, language='en-in')
        print("You said:", content)
        return content.lower()
    except sr.UnknownValueError:
        print("Could not understand audio")
        return ""
    except Exception as e:
        print(f"Error recognizing speech: {e}")
        speak("Please try again")
        return ""

# Weather Forecasting Function
def get_weather(city):
    api_key = "3f20034f8a17632b66cd59cce5a26803"
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
    response = requests.get(url)
    data = response.json()

    if data["cod"] == 200:  # Check if the API returns a successful response
        main = data["main"]
        weather = data["weather"][0]["description"]
        temperature = main["temp"]
        
        # Printing the weather details to the console
        print(f"The weather in {city} is {weather} with a temperature of {temperature}°C.")
        
        # Speaking the weather details
        speak(f"The weather in {city} is {weather} with a temperature of {temperature}°C.")
    else:
        if data["cod"] == "404":  # If the city is not found
            speak(f"Sorry, I couldn't find the weather for {city}. Please check the city name and try again.")
        else:
            speak("I encountered an error while fetching the weather. Please try again later.")

# Dictionary
def get_definition(word):
    synsets = wordnet.synsets(word)
    if synsets:
        definition = synsets[0].definition()
        return definition
    return "Sorry, I couldn't find the definition."

# Currency Converter
def convert_currency(amount, from_currency, to_currency):
    # Replace 'YOUR_API_KEY' with the actual API key you get from ExchangeRate-API
    api_key = '0280b78fdacd7de3468768bb'  # Replace this with your actual API key
    api_url = f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{from_currency}"
    
    try:
        # Convert the currencies to uppercase (the API expects uppercase codes)
        from_currency = from_currency.upper()
        to_currency = to_currency.upper()

        # Make the API request
        response = requests.get(api_url)
        data = response.json()
        
        # Check if the response is valid
        if data["result"] == "success":
            # Check if the target currency is in the conversion rates
            if to_currency in data["conversion_rates"]:
                converted_amount = amount * data["conversion_rates"][to_currency]
                
                # Speak and print the result
                result_message = f"{amount} {from_currency} is equal to {converted_amount} {to_currency}"
                print(result_message)
                speak(result_message)  # Speak the result
                
                return converted_amount
            else:
                error_message = f"Target currency '{to_currency}' not found."
                print(error_message)
                speak(error_message)  # Speak the error
                return None
        else:
            api_error_message = f"API error: {data.get('error-type', 'Unknown error')}"
            print(api_error_message)
            speak(api_error_message)  # Speak the error
            return None
    except Exception as e:
        error_message = f"Error occurred: {e}"
        print(error_message)
        speak(error_message)  # Speak the error
        return None

# Translator
def translate_text(text, target_language="en"):
    # Initialize the GoogleTranslator with the target language
    translator = GoogleTranslator(target=target_language)
    translation = translator.translate(text)
    return translation                

# News Broadcasting
def get_news_by_topic(topic):
    api_key = "fc59271d11a040d99fcb7566385da07b"  # Replace with your actual API key
    url = f"https://newsapi.org/v2/everything?q={topic}&apiKey={api_key}&language=en"
    response = requests.get(url)
    data = response.json()

    if data["status"] == "ok":
        articles = data["articles"]
        if not articles:
            speak(f"Sorry, I couldn't find any news on {topic}.")
            print(f"Sorry, I couldn't find any news on {topic}.")
        else:
            news = ""
            for article in articles[:5]:  # Get top 5 articles
                news += f"Title: {article['title']}\nDescription: {article['description']}\n\n"
            speak(f"Here are the top news stories on {topic}:")
            print(news)
            speak(news)
    else:
        speak("Sorry, I couldn't fetch the news at the moment.")

# Bitcoin Update
def get_bitcoin_price():
    url = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"
    response = requests.get(url)
    data = response.json()
    if "bitcoin" in data:
        price = data["bitcoin"]["usd"]
        speak(f"The current price of Bitcoin is ${price}")
        print(f"The current price of Bitcoin is ${price}")
    else:
        speak("Sorry, I couldn't fetch the Bitcoin price.")        

def gemini_response(query):
    try:
        past_conversation = load_history()
        prompt = (
            f"Previous conversation:\n{past_conversation}\n"
            f"User: {query}\nResponse:\n"
            "Keep your response very brief and concise, no more than 2-3 sentences maximum."
        )
        response = genai_client.models.generate_content(model=GEMINI_MODEL, contents=prompt)
        return response.text
    except Exception as e:
        print(f"[gemini_response ERROR] {type(e).__name__}: {e}")
        return f"[API error] {type(e).__name__}: {e}"

def _normalise(text: str) -> str:
    """Lower-case, expand common contractions, strip punctuation."""
    import re
    text = text.lower()
    # expand common contractions so voice/text both hit the same keyword
    text = text.replace("what's", "what is").replace("what's", "what is")
    text = text.replace("whats",  "what is")
    text = text.replace("it's",   "it is")
    text = text.replace("i'm",    "i am")
    text = text.replace("don't",  "do not")
    text = text.replace("can't",  "cannot")
    text = text.replace("won't",  "will not")
    text = text.replace("'",      "")   # strip remaining apostrophes
    # strip all punctuation except spaces
    text = re.sub(r"[^\w\s]", "", text)
    return text

def matches_command(request: str, keywords: list) -> bool:
    """Return True if the normalised request contains any normalised keyword."""
    norm_req = _normalise(request)
    return any(_normalise(kw) in norm_req for kw in keywords)

class JarvisThread(QThread):
    update_signal = QtCore.pyqtSignal(str)
    status_signal = QtCore.pyqtSignal(str)   # "IDLE" | "LISTENING" | "PROCESSING"

    def __init__(self):
        super().__init__()
        self.paused = False
        self.skip_current = False

    def run(self):
        speak("Hello, I am Jarvis. How can I help you?")
        while True:
            if self.paused:
                # While paused, only listen for "resume" command
                self.status_signal.emit("LISTENING")
                request = command()
                if matches_command(request, ["resume", "continue", "unpause", "start again"]):
                    speak("Resuming operation")
                    self.paused = False
                    self.update_signal.emit("Jarvis resumed.")
                time.sleep(0.5)
                continue

            self.status_signal.emit("LISTENING")
            request = command()
            self.status_signal.emit("PROCESSING")

            # ── Skip empty / noise grabs ───────────────────────────────────
            if not request or not request.strip():
                self.status_signal.emit("LISTENING")
                continue

            now = datetime.now()
            send_time_hour = now.hour
            send_time_minute = now.minute + 1

            # Check for pause command
            if matches_command(request, ["pause", "wait", "hold on", "stop listening"]):
                speak("Pausing operation. Say 'resume' to continue.")
                self.paused = True
                self.update_signal.emit("Jarvis paused.")
                self.status_signal.emit("IDLE")
                continue

            # Check for next/skip command
            if matches_command(request, ["next", "skip", "skip this", "next command"]):
                speak("Skipping current command. What would you like me to do instead?")
                self.update_signal.emit("Command skipped.")
                continue

            if matches_command(request, ["stop", "exit", "quit", "bye", "goodbye"]):
                self.update_signal.emit("Jarvis stopped.")
                self.status_signal.emit("IDLE")
                break
           
            elif matches_command(request, ["create powerpoint", "make presentation", "create presentation", "create a powerpoint", "make a powerpoint"]):
                generate_ppt()
            
            elif matches_command(request, ["what's the time", "what time is it", "tell me the time", "current time"]):
                t = now.strftime("%H:%M")
                speak("Current time: " + t)
            elif matches_command(request, ["what's the date", "what date is it", "tell me the date", "current date"]):
                t = now.strftime("%d-%m-%Y")
                speak("Current date: " + t)
            elif matches_command(request, ["add task", "new task", "create task"]):
                task = request.replace("new task", "").replace("add task", "").replace("create task", "").strip()
                if task:
                    with open("todo.txt", "a") as file:
                        file.write(task + "\n")
                    speak("Task added: " + task)
            elif matches_command(request, ["introduce yourself", "who are you", "tell me about yourself"]):
               ppt_file = "presentation.pptx"  # Change this to your actual file name
               if os.path.exists(ppt_file):
                    speak(f"SURE let me open this just to make you easy to understand myself ")
                    os.startfile(ppt_file)  # Open the PPT file
                    speak("Hello! I am Jarvis, your personal AI assistant, designed to make your digital experience seamless and efficient. Developed by Viraj Shinde, Vedant Surve, Shwet Kadam, and Saheem Nakhwa, I am here to handle all your PC tasks with just your voice.From opening applications, searching the web, and playing your favorite music to managing task lists and sending WhatsApp messages, I do it all. I also provide real-time updates on weather, stock market trends, and much more. And for intelligent, dynamic conversations, I am powered by Gemini AI, ensuring that no query goes unanswered.Your commands drive my actions, making your workflow smarter and faster. So, what can I do for you today?")
               else:
                    speak("PowerPoint file not found in the code directory.")

            elif matches_command(request, ["tell my task", "show my task", "read my tasks", "what are my tasks", "list my tasks"]):
                try:
                    with open("todo.txt", "r") as file:
                        tasks = file.read().strip()
                        if tasks:
                            speak("Today's tasks: " + tasks)
                        else:
                            speak("You have no tasks for today.")
                except FileNotFoundError:
                    speak("You don't have any tasks yet.")
            elif matches_command(request, ["show my task", "display my tasks", "notification tasks"]):
                try:
                    with open("todo.txt", "r") as file:
                        tasks = file.read().strip()
                        if tasks:
                            notification.notify(title="Today's Tasks", message=tasks)
                        else:
                            notification.notify(title="Today's Tasks", message="No tasks for today")
                except FileNotFoundError:
                    notification.notify(title="Today's Tasks", message="No tasks found")
            elif matches_command(request, ["open youtube", "launch youtube", "start youtube"]):
                speak("Opening YouTube")
                webbrowser.open("www.youtube.com")
            elif matches_command(request, ["play", "youtube play", "play song", "play music", "play video"]):
                song_name = request.replace("play", "").replace("jarvis", "").replace("youtube", "").replace("song", "").replace("music", "").replace("video", "").strip()
                if song_name:
                    speak(f"Playing {song_name} on YouTube")
                    pwkx.playonyt(song_name)
                else:
                     speak("Please specify a song name.")
                     
            elif matches_command(request, ["change tab", "switch tab", "next tab", "alt tab"]):
                speak("Changing tab")
                pyautogui.hotkey('alt','tab')
                
            elif matches_command(request, ["turn off", "shutdown", "shut down", "power off", "turn off system", "turn off computer"]):
                speak("Sure sir, shutting down your system")
                pyautogui.press("super")
                pyautogui.typewrite("shutdown")
                pyautogui.sleep(1)
                pyautogui.press("enter")
                
            elif "open" in request:
                query = request.replace("open", "").replace("jarvis", "").strip()
                speak(f"opening {query}")
                pyautogui.press("super")
                pyautogui.typewrite(query)
                pyautogui.sleep(1)
                pyautogui.press("enter")
            elif matches_command(request, ["take screenshot", "screenshot", "capture screen", "snap screen"]):
                speak("Taking screenshot")
                pyautogui.screenshot("my_screenshot.png")
            elif matches_command(request, ["wikipedia", "search wikipedia", "look up wikipedia"]):
                search_query = request.replace("wikipedia", "").replace("search", "").replace("about", "").replace("jarvis", "").replace("look up", "").strip()
                try:
                    result = wikipedia.summary(search_query, sentences=3)
                    speak(f"searching wikipedia about {search_query}")
                    self.update_signal.emit(result)
                    speak(result)
                except Exception as e:
                    speak(f"Sorry, I couldn't find information about {search_query} on Wikipedia")
            elif matches_command(request, ["search google", "google", "search the web", "look up google"]):
                search_query = request.replace("search google", "").replace("google", "").replace("search", "").replace("about", "").replace("jarvis", "").replace("the web", "").replace("look up", "").strip()
                speak(f"searching google for {search_query}")
                webbrowser.open(f"https://www.google.com/search?q={search_query}")
            
            elif matches_command(request, ["send whatsapp", "whatsapp message", "send message", "message on whatsapp"]):
                # You could expand this to ask for the number and message
                pwkx.sendwhatmsg("+91 75070 44999", "Hi, my wp is not running so i am sending this message from jarvis .", send_time_hour, send_time_minute)
                speak("sending message")
            
            elif matches_command(request, ["show history", "conversation history", "chat history", "show chat"]):
                history = load_history()
                if history:
                    speak("Reading conversation history.")
                    speak(history)
                else:
                    speak("No conversation history found.")
            elif matches_command(request, ["clear history", "delete history", "remove history", "clean history"]):
                clear_history()

            elif matches_command(request, ["weather", "weather forecast", "temperature"]):
                city = request.replace("weather", "").replace("in", "").replace("forecast", "").replace("temperature", "").replace("jarvis", "").strip()
                if not city:
                    speak("Please specify a city for the weather forecast.")
                else:
                    get_weather(city)

            elif matches_command(request, ["define", "definition", "meaning","tell"]):
                word = request.replace("define", "").replace("definition", "").replace("meaning", "").replace("what is", "").replace("what's", "").replace("jarvis", "").strip()
                definition = get_definition(word)
                speak(definition)

            elif matches_command(request, ["convert currency", "currency conversion", "exchange rate"]):
             try:
                # Process even if input doesn't perfectly match the expected format
                request_lower = request.lower()
                if "to" in request_lower:
                    parts = request_lower.split("to")
                    amount_part = parts[0]
                    to_currency = parts[1].strip()
                    
                    # Extract the amount and from_currency from the first part
                    words = amount_part.split()
                    amount = None
                    from_currency = None
                    
                    for i, word in enumerate(words):
                        # Try to parse word as a number
                        try:
                            amount = float(word)
                            # If we found the amount and there's a next word, it's likely the currency
                            if i + 1 < len(words):
                                from_currency = words[i + 1]
                            break
                        except ValueError:
                            continue
                    
                    if amount is not None and from_currency is not None and to_currency:
                        conversion_result = convert_currency(amount, from_currency, to_currency)
                        if conversion_result:
                            speak(f"{amount} {from_currency} is equal to {conversion_result} {to_currency}")
                        else:
                            speak("Sorry, I couldn't convert the currency.")
                    else:
                        speak("Please provide both currencies and an amount. For example: 'convert currency 100 USD to EUR'")
                else:
                    speak("Please provide the currency to convert to. Example: 'convert currency 100 USD to EUR'")
             except Exception as e:
                speak("Sorry, I encountered an error with the currency conversion.")
                print(f"Error: {e}")   

            elif matches_command(request, ["translate", "translation", "convert language"]):
             try:
                # More flexible handling of translation requests
                request_lower = request.lower()
                if "to" in request_lower:
                    parts = request_lower.split("to")
                    text_part = parts[0]
                    target_language = parts[1].strip()
                    
                    # Remove common leading words
                    text = text_part.replace("translate", "").replace("translation", "").replace("convert", "").replace("language", "").replace("jarvis", "").strip()
                    
                    if text and target_language:
                        translation = translate_text(text, target_language)
                        speak(f"The translation is: {translation}")
                        print(f"Translation of '{text}' to {target_language}: {translation}")
                    else:
                        speak("I need a text to translate and a target language.")
                else:
                    speak("Please tell me the language to translate to. For example: 'translate hello to Spanish'")
             except Exception as e:
               speak(f"Sorry, I couldn't process the translation. Error: {e}")
               print(f"Error: {e}")

            elif matches_command(request, ["news", "latest news", "news on", "news about"]):
             topic = request.replace("news", "").replace("on", "").replace("about", "").replace("latest", "").replace("jarvis", "").strip()
             if topic:
                 get_news_by_topic(topic)
             else:
                 speak("Please specify a topic. For example, you can say 'news on technology'.")

            elif matches_command(request, ["bitcoin", "bitcoin price", "crypto", "cryptocurrency", "crypto price"]):
                 get_bitcoin_price()
                 
            elif matches_command(request,["cube","rubiks cube","rubiks cube final step formula"]):
                speak("Ha    ha     ha         you dumb, how can you forget that")
                speak("its R prime D prime R D")
                
            
            elif matches_command(request,["chess","i want to try chess"]):
                speak("Hope you dont loose to a low rated player")
                webbrowser.open("https://www.chess.com/play")
    
            else:
                response = gemini_response(request)
                self.update_signal.emit(f"You: {request}\nJarvis: {response}")
                speak(response)
                save_history(request, response)

# ─── Shared stylesheet constants ────────────────────────────────────────────
_HUD_FONT       = "Consolas, 'Courier New', monospace"
_CYAN           = "#00E5FF"
_STATUS_COLORS  = {"IDLE": "#607D8B", "LISTENING": "#00E5FF", "PROCESSING": "#FF9100"}

_BTN_RUN = """
    QPushButton {
        background-color: rgba(0,20,30,0.85);
        color: #00E5FF;
        font-family: Consolas, 'Courier New', monospace;
        font-size: 15px;
        font-weight: bold;
        letter-spacing: 3px;
        border-radius: 6px;
        border: 2px solid #00E5FF;
        padding: 4px 16px;
    }
    QPushButton:hover {
        background-color: rgba(0,229,255,0.18);
        border: 2px solid #80FFFF;
        color: #FFFFFF;
    }
    QPushButton:pressed {
        background-color: rgba(0,229,255,0.35);
        border: 2px solid #00E5FF;
    }
"""

_BTN_STOP = """
    QPushButton {
        background-color: rgba(30,0,0,0.85);
        color: #FF4D6A;
        font-family: Consolas, 'Courier New', monospace;
        font-size: 15px;
        font-weight: bold;
        letter-spacing: 3px;
        border-radius: 6px;
        border: 2px solid #FF4D6A;
        padding: 4px 16px;
    }
    QPushButton:hover {
        background-color: rgba(255,77,106,0.18);
        border: 2px solid #FF8099;
        color: #FFFFFF;
    }
    QPushButton:pressed {
        background-color: rgba(255,77,106,0.35);
        border: 2px solid #FF4D6A;
    }
"""

_TEXT_BROWSER = """
    QTextBrowser {
        background-color: rgba(0, 8, 18, 0.72);
        color: #00FF88;
        font-family: Consolas, 'Courier New', monospace;
        font-size: 13px;
        border: 1px solid rgba(0,229,255,0.45);
        border-left: 3px solid #00E5FF;
        border-radius: 4px;
        padding: 6px 10px;
        selection-background-color: #00E5FF;
        selection-color: #000000;
    }
    QScrollBar:vertical {
        background: rgba(0,0,0,0);
        width: 6px;
        margin: 0px;
    }
    QScrollBar::handle:vertical {
        background: #00E5FF;
        border-radius: 3px;
        min-height: 20px;
    }
    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0px; }
    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { background: none; }
"""

_CLOCK_STYLE = """
    QLabel {
        background: transparent;
        color: #00E5FF;
        font-family: Consolas, 'Courier New', monospace;
        font-size: 15px;
        font-weight: bold;
        letter-spacing: 2px;
    }
"""

_STATUS_BASE = """
    QLabel {{
        background: rgba(0,8,18,0.7);
        color: {color};
        font-family: Consolas, 'Courier New', monospace;
        font-size: 11px;
        font-weight: bold;
        letter-spacing: 2px;
        border: 1px solid {color};
        border-radius: 3px;
        padding: 1px 8px;
    }}
"""

# ─── Custom title bar widget ─────────────────────────────────────────────────
class _TitleBar(QtWidgets.QWidget):
    """Thin frameless title bar with drag support and min/close buttons."""

    def __init__(self, parent):
        super().__init__(parent)
        self.parent_win = parent
        self._drag_pos = None
        self.setFixedHeight(32)
        self.setAttribute(QtCore.Qt.WA_StyledBackground, True)
        self.setStyleSheet(
            "background: rgba(0,8,22,0.90);"
            "border-bottom: 1px solid rgba(0,229,255,0.30);"
        )

        layout = QtWidgets.QHBoxLayout(self)
        layout.setContentsMargins(10, 0, 6, 0)
        layout.setSpacing(0)

        title = QtWidgets.QLabel("J.A.R.V.I.S.  //  ENDGAME INTERFACE")
        title.setStyleSheet(
            "color: #00E5FF; font-family: Consolas,'Courier New',monospace;"
            "font-size: 12px; font-weight: bold; letter-spacing: 3px;"
            "background: transparent; border: none;"
        )
        layout.addWidget(title)
        layout.addStretch()

        btn_min_style = (
            "QPushButton{background:transparent;color:#888;font-size:14px;"
            "border:none;min-width:28px;min-height:28px;}"
            "QPushButton:hover{color:#fff;background:rgba(255,255,255,0.08);}"
        )
        btn_close_style = (
            "QPushButton{background:transparent;color:#FF4D6A;font-size:14px;"
            "border:none;min-width:28px;min-height:28px;}"
            "QPushButton:hover{background:#FF4D6A;color:#fff;}"
        )

        self.btn_min = QtWidgets.QPushButton("—")
        self.btn_min.setStyleSheet(btn_min_style)
        self.btn_min.clicked.connect(lambda: parent.showMinimized())

        self.btn_close = QtWidgets.QPushButton("✕")
        self.btn_close.setStyleSheet(btn_close_style)
        self.btn_close.clicked.connect(lambda: parent.close())

        layout.addWidget(self.btn_min)
        layout.addWidget(self.btn_close)

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self._drag_pos = event.globalPos() - self.parent_win.frameGeometry().topLeft()

    def mouseMoveEvent(self, event):
        if self._drag_pos and event.buttons() == QtCore.Qt.LeftButton:
            self.parent_win.move(event.globalPos() - self._drag_pos)

    def mouseReleaseEvent(self, event):
        self._drag_pos = None

    def mouseDoubleClickEvent(self, event):
        if self.parent_win.isMaximized():
            self.parent_win.showNormal()
        else:
            self.parent_win.showMaximized()


# ─── Main UI class ───────────────────────────────────────────────────────────
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # ── Window chrome ──────────────────────────────────────────────────
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1317, 806)
        MainWindow.setWindowTitle("J.A.R.V.I.S.")
        MainWindow.setWindowFlags(
            QtCore.Qt.FramelessWindowHint | QtCore.Qt.Window
        )

        # ── Central widget ─────────────────────────────────────────────────
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: black;")

        # ── GIF background (shifted 32 px down to leave room for title bar) ─
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 32, 1317, 774))
        self.movie = QtGui.QMovie("gui.gif")
        self.label.setMovie(self.movie)
        self.movie.start()
        self.label.setScaledContents(True)

        # ── Custom title bar ───────────────────────────────────────────────
        self.title_bar = _TitleBar(self.centralwidget)
        self.title_bar.setGeometry(0, 0, 1317, 32)

        # ── Conversation log ───────────────────────────────────────────────
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(530, 283, 471, 325))
        self.textBrowser_2.setStyleSheet(_TEXT_BROWSER)

        # ── Status indicator ───────────────────────────────────────────────
        self.lbl_status = QtWidgets.QLabel("●  IDLE", self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(700, 253, 130, 22))
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setStyleSheet(_STATUS_BASE.format(color=_STATUS_COLORS["IDLE"]))

        # ── RUN button ─────────────────────────────────────────────────────
        self.pushButton_2 = QtWidgets.QPushButton("▶  RUN", self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(558, 636, 150, 44))
        self.pushButton_2.setStyleSheet(_BTN_RUN)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        # ── STOP button ────────────────────────────────────────────────────
        self.pushButton_3 = QtWidgets.QPushButton("■  STOP", self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(814, 636, 150, 44))
        self.pushButton_3.setStyleSheet(_BTN_STOP)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        # ── Clock label (top-left) ─────────────────────────────────────────
        self.lbl_clock = QtWidgets.QLabel("", self.centralwidget)
        self.lbl_clock.setGeometry(QtCore.QRect(80, 38, 200, 24))
        self.lbl_clock.setStyleSheet(_CLOCK_STYLE)

        # ── Date label (top-right) ─────────────────────────────────────────
        self.lbl_date = QtWidgets.QLabel("", self.centralwidget)
        self.lbl_date.setGeometry(QtCore.QRect(1040, 38, 200, 24))
        self.lbl_date.setStyleSheet(_CLOCK_STYLE)
        self.lbl_date.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)

        # ── Text input field ───────────────────────────────────────────────
        self.txt_input = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_input.setGeometry(QtCore.QRect(530, 690, 360, 38))
        self.txt_input.setPlaceholderText("Type a command and press Enter or Send…")
        self.txt_input.setStyleSheet("""
            QLineEdit {
                background-color: rgba(0, 8, 18, 0.80);
                color: #00FF88;
                font-family: Consolas, 'Courier New', monospace;
                font-size: 13px;
                border: 1px solid rgba(0,229,255,0.45);
                border-left: 3px solid #00E5FF;
                border-radius: 4px;
                padding: 4px 10px;
                selection-background-color: #00E5FF;
                selection-color: #000000;
            }
            QLineEdit:focus {
                border: 1px solid #00E5FF;
                border-left: 3px solid #00E5FF;
            }
        """)

        # ── Send button ────────────────────────────────────────────────────
        self.btn_send = QtWidgets.QPushButton("SEND", self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(898, 690, 103, 38))
        self.btn_send.setStyleSheet("""
            QPushButton {
                background-color: rgba(0,20,30,0.85);
                color: #00E5FF;
                font-family: Consolas, 'Courier New', monospace;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 2px;
                border-radius: 4px;
                border: 1px solid #00E5FF;
                padding: 4px 10px;
            }
            QPushButton:hover {
                background-color: rgba(0,229,255,0.18);
                border: 1px solid #80FFFF;
                color: #FFFFFF;
            }
            QPushButton:pressed {
                background-color: rgba(0,229,255,0.35);
            }
        """)
        self.btn_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        # ── Raise all overlays above GIF ───────────────────────────────────
        for w in (self.title_bar, self.lbl_clock, self.lbl_date,
                  self.textBrowser_2, self.lbl_status,
                  self.pushButton_2, self.pushButton_3,
                  self.txt_input, self.btn_send):
            w.raise_()

        # ── Wire up ────────────────────────────────────────────────────────
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_2.clicked.connect(self.start_jarvis)
        self.pushButton_3.clicked.connect(self.stop_jarvis)
        self.btn_send.clicked.connect(self.send_text)
        self.txt_input.returnPressed.connect(self.send_text)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_time)
        self.timer.start(1000)
        self.update_time()   # populate immediately on startup

        self.jarvis_thread = None


    # ── Clock update ───────────────────────────────────────────────────────
    def update_time(self):
        now = datetime.now()
        self.lbl_clock.setText(now.strftime("⏱  %H:%M:%S"))
        self.lbl_date.setText(now.strftime("%d-%m-%Y"))

    # ── Status dot ─────────────────────────────────────────────────────────
    def update_status(self, state: str):
        color = _STATUS_COLORS.get(state, "#607D8B")
        self.lbl_status.setText(f"●  {state}")
        self.lbl_status.setStyleSheet(_STATUS_BASE.format(color=color))

    # ── Text command send ───────────────────────────────────────────────────
    def send_text(self):
        text = self.txt_input.text().strip()
        if not text:
            return
        self.txt_input.clear()

        if not self.jarvis_thread or not self.jarvis_thread.isRunning():
            self.textBrowser_2.append(
                '<span style="color:#FF9100;">⚠ Start JARVIS first (▶ RUN)</span>'
            )
            return

        # Echo immediately in the log
        self.textBrowser_2.append(f'<span style="color:#00E5FF;">You: {text}</span>')
        # Push into queue — command() will pick it up on the next loop tick
        _text_queue.put(text)

    # ── Jarvis controls ────────────────────────────────────────────────────
    def start_jarvis(self):
        if self.jarvis_thread and self.jarvis_thread.isRunning():
            return
        self.textBrowser_2.clear()
        self.textBrowser_2.append("[ JARVIS ONLINE ]")
        self.jarvis_thread = JarvisThread()
        self.jarvis_thread.update_signal.connect(self.textBrowser_2.append)
        self.jarvis_thread.status_signal.connect(self.update_status)
        self.update_status("LISTENING")
        self.jarvis_thread.start()

    def stop_jarvis(self):
        self.update_status("IDLE")
        if self.jarvis_thread:
            self.jarvis_thread.terminate()
        speak("Shutting down")
        QtWidgets.qApp.quit()


# ─── Draggable main window ───────────────────────────────────────────────────
class MovableMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MovableMainWindow, self).__init__()
        self.oldPos = None

    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def mouseMoveEvent(self, event):
        if self.oldPos:
            delta = QtCore.QPoint(event.globalPos() - self.oldPos)
            self.move(self.x() + delta.x(), self.y() + delta.y())
            self.oldPos = event.globalPos()

class FaceRecognitionThread(QThread):
    update_frame = QtCore.pyqtSignal(QImage)
    authentication_result = QtCore.pyqtSignal(bool)
    
    def __init__(self, reference_image_path):
        super().__init__()
        self.reference_image_path = reference_image_path
        self.running = True
        
    def run(self):
        # Load face cascade for simple face detection - no dlib required
        try:
            face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
            
            # Access webcam (use camera index 1 for DroidCam)
            cap = cv2.VideoCapture(0)  # Changed from 0 to 1 for DroidCam
            if not cap.isOpened():
                print("Cannot open camera")
                self.authentication_result.emit(False)
                return
                
            face_detected_frames = 0
            required_frames = 20  # Need to detect face in 20 frames to authenticate
            attempts = 0
            max_attempts = 100  # About 10 seconds of trying
            
            while self.running and attempts < max_attempts:
                ret, frame = cap.read()
                if not ret:
                    print("Can't receive frame. Exiting...")
                    break
                    
                # Convert to grayscale for face detection
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                
                # Detect faces
                faces = face_cascade.detectMultiScale(gray, 1.3, 5)
                
                # Add visual effects to frame
                # Add a border
                frame = cv2.copyMakeBorder(frame, 10, 10, 10, 10, cv2.BORDER_CONSTANT, value=[0, 120, 255])
                
                # Add scanning effect overlay
                overlay = frame.copy()
                # Draw horizontal scan line
                scan_position = (attempts % 50) * (frame.shape[0] // 50)
                cv2.line(overlay, (0, scan_position), (frame.shape[1], scan_position), (0, 255, 0), 2)
                frame = cv2.addWeighted(overlay, 0.7, frame, 0.3, 0)
                
                # Add system status text
                cv2.putText(frame, "JARVIS SECURITY SYSTEM", (frame.shape[1]//2 - 150, 30), 
                          cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
                
                if len(faces) > 0:
                    # Face detected
                    face_detected_frames += 1
                    
                    # Draw rectangle around face
                    for (x, y, w, h) in faces:
                        # Draw fancy rectangle
                        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
                        
                        # Draw corner lines for futuristic look
                        corner_length = 20
                        # Top left
                        cv2.line(frame, (x, y), (x + corner_length, y), (0, 255, 255), 2)
                        cv2.line(frame, (x, y), (x, y + corner_length), (0, 255, 255), 2)
                        # Top right
                        cv2.line(frame, (x+w, y), (x+w - corner_length, y), (0, 255, 255), 2)
                        cv2.line(frame, (x+w, y), (x+w, y + corner_length), (0, 255, 255), 2)
                        # Bottom left
                        cv2.line(frame, (x, y+h), (x + corner_length, y+h), (0, 255, 255), 2)
                        cv2.line(frame, (x, y+h), (x, y+h - corner_length), (0, 255, 255), 2)
                        # Bottom right
                        cv2.line(frame, (x+w, y+h), (x+w - corner_length, y+h), (0, 255, 255), 2)
                        cv2.line(frame, (x+w, y+h), (x+w, y+h - corner_length), (0, 255, 255), 2)
                        
                        progress = min(face_detected_frames / required_frames, 1.0)
                        bar_width = int(w * progress)
                        
                        # Draw progress bar
                        cv2.rectangle(frame, (x, y+h+5), (x+bar_width, y+h+15), (0, 255, 0), -1)
                        cv2.rectangle(frame, (x, y+h+5), (x+w, y+h+15), (255, 255, 255), 1)
                        
                        # Progress percentage
                        percentage = int(progress * 100)
                        cv2.putText(frame, f"Scanning: {percentage}%", (x, y+h+30), 
                                  cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                    
                    # Check if we have enough consistent detections
                    if face_detected_frames >= required_frames:
                        # Authentication successful
                        # Create success overlay
                        success_overlay = frame.copy()
                        cv2.rectangle(success_overlay, (0, 0), (frame.shape[1], frame.shape[0]), (0, 255, 0), -1)
                        
                        # Blend with original frame
                        frame = cv2.addWeighted(success_overlay, 0.3, frame, 0.7, 0)
                        
                        # Add success text
                        cv2.putText(frame, "ACCESS GRANTED", (frame.shape[1]//2 - 150, frame.shape[0]//2), 
                                  cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 3)
                        cv2.putText(frame, "AUTHENTICATION SUCCESSFUL", (frame.shape[1]//2 - 200, frame.shape[0]//2 + 50), 
                                  cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
                        
                        # Convert frame to QImage and emit
                        h, w, ch = frame.shape
                        qt_image = QImage(frame.data, w, h, ch * w, QImage.Format_RGB888)
                        self.update_frame.emit(qt_image.rgbSwapped())
                        
                        # Wait a moment to display the success message
                        time.sleep(1.5)
                        
                        # Authentication successful - speak confirmation
                        speak("Authentication successful. Welcome back, sir.")
                        
                        # Authentication successful
                        cap.release()
                        print("Authentication successful, emitting True signal")
                        self.authentication_result.emit(True)
                        return
                else:
                    # Reset counter if face is lost
                    face_detected_frames = max(0, face_detected_frames - 1)
                    # Warning text
                    cv2.putText(frame, "No face detected", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
                    cv2.putText(frame, "Please position your face in the camera view", (50, 80), 
                              cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
                
                # Add scanning line effect
                
                # Convert frame to QImage and emit
                h, w, ch = frame.shape
                qt_image = QImage(frame.data, w, h, ch * w, QImage.Format_RGB888)
                self.update_frame.emit(qt_image.rgbSwapped())
                
                attempts += 1
                time.sleep(0.1)
                
            # If we get here without successful authentication
            cap.release()
            speak("Authentication failed. Access denied.")
            print("Authentication failed, emitting False signal")
            self.authentication_result.emit(False)
        except Exception as e:
            print(f"Error in facial recognition: {e}")
            # In case of error, still try to proceed with authentication
            speak("Authentication system error. Proceeding with startup.")
            self.authentication_result.emit(True)
    
    def stop(self):
        self.running = False
        self.wait()

class FaceAuthenticationWindow(QtWidgets.QMainWindow):
    def __init__(self, reference_image_path="face_reference.jpg"):
        super().__init__()
        self.reference_image_path = reference_image_path
        print("Initializing FaceAuthenticationWindow")
        self.initUI()
        
    def initUI(self):
        self.setWindowTitle('JARVIS Security System')
        self.setGeometry(100, 100, 800, 600)
        self.setStyleSheet("background-color: #1E1E1E;")
        
        # Set window icon
        try:
            self.setWindowIcon(QtGui.QIcon("jarvis_icon.png"))
        except Exception as e:
            print(f"Error setting window icon: {e}")
        
        # Central widget
        central_widget = QtWidgets.QWidget()
        self.setCentralWidget(central_widget)
        
        # Main layout
        main_layout = QtWidgets.QVBoxLayout(central_widget)
        main_layout.setContentsMargins(20, 20, 20, 20)
        
        # Title label
        title_label = QtWidgets.QLabel("JARVIS SECURITY AUTHENTICATION")
        title_label.setAlignment(QtCore.Qt.AlignCenter)
        title_label.setStyleSheet("color: #00A9F4; font-size: 24px; font-weight: bold; margin-bottom: 10px;")
        main_layout.addWidget(title_label)
        
        # Video frame with border
        video_frame = QtWidgets.QFrame()
        video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        video_frame.setStyleSheet("border: 2px solid #00A9F4; border-radius: 10px; padding: 5px; background-color: #2D2D30;")
        video_layout = QtWidgets.QVBoxLayout(video_frame)
        
        # Video display label
        self.video_label = QtWidgets.QLabel()
        self.video_label.setMinimumSize(700, 450)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setStyleSheet("border: none;")
        video_layout.addWidget(self.video_label)
        
        main_layout.addWidget(video_frame)
        
        # Status label
        self.status_label = QtWidgets.QLabel("Initializing facial recognition system...")
        self.status_label.setStyleSheet("font-size: 18px; color: #00A9F4; margin-top: 10px;")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.status_label)
        
        # Start face recognition with voice prompt
        print("Setting up face recognition timer")
        speak("Initializing security systems")
        QTimer.singleShot(1500, self.start_face_recognition)
    
    def start_face_recognition(self):
        print("Starting face recognition")
        speak("Beginning facial authentication")
        self.status_label.setText("Looking for your face...")
        # Create and start the face recognition thread
        self.face_thread = FaceRecognitionThread(self.reference_image_path)
        print("Connecting signals")
        self.face_thread.update_frame.connect(self.update_frame)
        self.face_thread.authentication_result.connect(self.handle_authentication)
        print("Starting face thread")
        self.face_thread.start()
    
    def update_frame(self, qt_image):
        pixmap = QPixmap.fromImage(qt_image)
        self.video_label.setPixmap(pixmap.scaled(self.video_label.width(), self.video_label.height(), QtCore.Qt.KeepAspectRatio))
    
    def handle_authentication(self, success):
        print(f"Authentication result: {success}")
        if success:
            self.status_label.setText("Authentication Successful! Launching JARVIS...")
            self.status_label.setStyleSheet("font-size: 18px; color: #00FF00; margin-top: 10px;")
            # Wait a moment to display the success message
            print("Setting up launch timer")
            QTimer.singleShot(2000, self.launch_jarvis)
        else:
            self.status_label.setText("Authentication Failed! Access Denied.")
            self.status_label.setStyleSheet("font-size: 18px; color: #FF0000; margin-top: 10px;")
            # Wait a moment and then close the application
            QTimer.singleShot(3000, self.close)
    
    def launch_jarvis(self):
        print("Launch method called")
        try:
            # Close the authentication window
            print("Closing authentication window")
            self.close()
            
            # Launch Jarvis in a new process
            print("Launching Jarvis in new process")
            # Use subprocess to launch a new instance with the --gui-only flag
            subprocess.Popen([sys.executable, "endgame.py", "--gui-only"])
            
            # Exit this process
            print("Exiting authentication process")
            sys.exit(0)
        except Exception as e:
            print(f"Error launching Jarvis: {e}")
            with open("jarvis_error.log", "w") as file:
                file.write(f"Error launching Jarvis: {e}")

    def closeEvent(self, event):
        # Stop the face recognition thread when closing the window
        if hasattr(self, 'face_thread'):
            self.face_thread.stop()
        event.accept()

def save_reference_image():
    """Capture and save a reference image of the user's face"""
    if os.path.exists("face_reference.jpg"):
        return  # Reference image already exists
        
    print("Capturing reference image of your face...")
    cap = cv2.VideoCapture(0)  # Changed from 0 to 1 for DroidCam
    if not cap.isOpened():
        print("Cannot open camera")
        return False
        
    # Wait a bit to let the camera adjust
    for _ in range(10):
        cap.read()
        time.sleep(0.1)
    
    ret, frame = cap.read()
    cap.release()
    
    if ret:
        # Save the reference image
        cv2.imwrite("face_reference.jpg", frame)
        print("Reference image saved as 'face_reference.jpg'")
        return True
    else:
        print("Failed to capture reference image")
        return False

def launch_jarvis_standalone():
    """Standalone function to launch Jarvis directly"""
    try:
        print("Launching Jarvis standalone")
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = MovableMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        print("Jarvis GUI should be visible now")
        sys.exit(app.exec_())
    except Exception as e:
        print(f"Error in standalone launch: {e}")
        with open("standalone_error.log", "w") as f:
            f.write(f"Standalone launch error: {e}")

if __name__ == "__main__":
    # Check if --gui-only flag is set (just launch the main GUI directly)
    if len(sys.argv) > 1 and sys.argv[1] == "--gui-only":
        print("Running in GUI-only mode - bypassing authentication")
        launch_jarvis_standalone()
        sys.exit(0)

    # Create ONE QApplication for the entire lifetime of the process
    app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv)

    try:
        # Check if running in test mode (without camera)
        if len(sys.argv) > 1 and sys.argv[1] == "--no-camera":
            print("Running in test mode - bypassing face authentication")
            MainWindow = MovableMainWindow()
            ui = Ui_MainWindow()
            ui.setupUi(MainWindow)
            MainWindow.show()
            sys.exit(app.exec_())

        # Check if reference image exists, otherwise create one
        if not os.path.exists("face_reference.jpg"):
            # If no reference image, show a setup dialog
            msgBox = QtWidgets.QMessageBox()
            msgBox.setWindowTitle("First Time Setup")
            msgBox.setText("No reference face image found. Would you like to capture one now? (Or run with --no-camera flag to bypass)")
            msgBox.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
            msgBox.setDefaultButton(QtWidgets.QMessageBox.Yes)

            if msgBox.exec_() == QtWidgets.QMessageBox.Yes:
                save_reference_image()
            else:
                sys.exit()

        # Start the authentication window
        try:
            window = FaceAuthenticationWindow()
            window.show()
            sys.exit(app.exec_())
        except Exception as auth_error:
            print(f"Error in face authentication window: {auth_error}")
            with open("auth_error.log", "w") as f:
                f.write(f"Authentication window error: {auth_error}")

            # Fallback to direct launching if authentication window fails
            print("Falling back to direct launch")
            MainWindow = MovableMainWindow()
            ui = Ui_MainWindow()
            ui.setupUi(MainWindow)
            MainWindow.show()
            sys.exit(app.exec_())
    except Exception as main_error:
        # This catches any error in the main block
        print(f"Critical error in main: {main_error}")
        with open("critical_error.log", "w") as f:
            f.write(f"Critical error: {main_error}")

        # Last resort - extremely simple window launch
        try:
            import traceback
            traceback.print_exc()
            with open("traceback.log", "w") as f:
                traceback.print_exc(file=f)

            main_win = QtWidgets.QMainWindow()
            ui = Ui_MainWindow()
            ui.setupUi(main_win)
            main_win.show()
            sys.exit(app.exec_())
        except Exception as last_error:
            print(f"Final fallback failed: {last_error}")
            with open("final_error.log", "w") as f:
                f.write(f"Final fallback failed: {last_error}")