import sys
import pyttsx3
import speech_recognition as sr
import webbrowser
import datetime
import os
import pyautogui
import wikipedia
import pywhatkit as pwk
import google.generativeai as genai
from pptx import Presentation
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread

# Gemini AI Configuration
genai.configure(api_key="AIzaSyCjGZozlCwigt4S4Zn7kvuGMXDLyyFEAxI")
model = genai.GenerativeModel('gemini-1.5-flash')

# Initialize Text-to-Speech
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
engine.setProperty('rate', 180)

def speak(audio):
    """Convert text to speech."""
    engine.say(audio)
    engine.runAndWait()

def command():
    """Listen to voice command and return as text."""
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        audio = r.listen(source)
    try:
        content = r.recognize_google(audio, language='en-in')
        print("You said:", content)
        return content.lower()
    except Exception:
        speak("Please try again")
        return ""

def gemini_response(query):
    """Generate AI response using Gemini."""
    try:
        response = model.generate_content(query)
        return response.text
    except Exception:
        return "I am sorry, I could not process that."

def generate_ppt():
    """Generate a PowerPoint presentation from voice input."""
    speak("Please say the topic for your PowerPoint presentation.")
    topic = command()
    
    if not topic:
        speak("No topic detected. Please try again.")
        return

    speak(f"Generating a presentation on {topic}. Please wait.")
    
    try:
        # Generate content using Gemini AI
        prompt = f"Create an educational PowerPoint outline on {topic}. Include a title slide and 4-5 key slides with summarized points."
        response = model.generate_content(prompt)
        slides_content = response.text.split("\n\n")  # Split text into slides

        # Create PowerPoint
        ppt = Presentation()

        # Title Slide
        slide_layout = ppt.slide_layouts[0]
        slide = ppt.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"{topic}"
        subtitle.text = "Generated by Jarvis AI"

        # Add Content Slides
        for slide_text in slides_content:
            slide_layout = ppt.slide_layouts[1]  # Title & Content Layout
            slide = ppt.slides.add_slide(slide_layout)
            title, content = slide.shapes.title, slide.placeholders[1]

            slide_parts = slide_text.split(": ", 1)
            if len(slide_parts) == 2:
                title.text, content.text = slide_parts
            else:
                title.text, content.text = topic, slide_text

        # Save the presentation
        ppt_filename = f"{topic.replace(' ', '_')}.pptx"
        ppt.save(ppt_filename)

        speak(f"Presentation on {topic} has been created successfully. Opening the file now.")
        os.startfile(ppt_filename)

    except Exception as e:
        speak("I encountered an error while generating the presentation.")
        print("Error:", e)

class JarvisThread(QThread):
    update_signal = QtCore.pyqtSignal(str)

    def run(self):
        speak("Hello, I am Jarvis. How can I help you?")
        while True:
            request = command()
            if "stop" in request:
                self.update_signal.emit("Jarvis stopped.")
                break
            elif "what's the time" in request:
                speak(datetime.datetime.now().strftime("%H:%M"))
            elif "what's the date" in request:
                speak(datetime.datetime.now().strftime("%d-%m-%Y"))
            elif "open youtube" in request:
                webbrowser.open("www.youtube.com")
            elif "search google" in request:
                search_query = request.replace("search google ", "").strip()
                speak(f"Searching {search_query} on Google")
                webbrowser.open(f"https://www.google.com/search?q={search_query}")
            elif "wikipedia" in request:
                search_query = request.replace("search wikipedia about ", "").strip()
                result = wikipedia.summary(search_query, sentences=3)
                speak(result)
            elif "play" in request:
                song_name = request.replace("play ", "").strip()
                if song_name:
                    speak(f"Playing {song_name} on YouTube")
                    pwk.playonyt(song_name)
            elif "create a powerpoint" in request:
                generate_ppt()
            else:
                response = gemini_response(request)
                self.update_signal.emit(f"You: {request}\nJarvis: {response}")
                speak(response)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1317, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -60, 1341, 851))
        self.label.setPixmap(QtGui.QPixmap("gui.gif"))
        self.label.setScaledContents(True)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(530, 251, 471, 361))
        self.pushButton_2 = QtWidgets.QPushButton("RUN", self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 640, 101, 31))
        self.pushButton_3 = QtWidgets.QPushButton("STOP", self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 640, 101, 31))
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(140, 10, 191, 31))
        self.textBrowser_3.setStyleSheet("background:transparent;")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1070, 10, 191, 31))
        self.textBrowser_4.setStyleSheet("background:transparent;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_2.clicked.connect(self.start_jarvis)
        self.pushButton_3.clicked.connect(self.stop_jarvis)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_time)
        self.timer.start(1000)
        self.jarvis_thread = None

    def update_time(self):
        self.textBrowser_3.setText(datetime.datetime.now().strftime("%H:%M:%S"))
        self.textBrowser_4.setText(datetime.datetime.now().strftime("%d-%m-%Y"))

    def start_jarvis(self):
        self.textBrowser_2.append("Jarvis started...")
        self.jarvis_thread = JarvisThread()
        self.jarvis_thread.update_signal.connect(self.textBrowser_2.append)
        self.jarvis_thread.start()

    def stop_jarvis(self):
        if self.jarvis_thread:
            self.jarvis_thread.terminate()
        speak("Shutting down")
        QtWidgets.qApp.quit()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
