import sys
import os
import cv2
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QThread, pyqtSignal
from PyQt5.QtGui import QImage, QPixmap
import time
import subprocess
import pyttsx3
import speech_recognition as sr
import random
import webbrowser
import datetime
from datetime import datetime
from plyer import notification
import pyautogui
import wikipedia
import pywhatkit as pwk
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import requests
from PIL import Image
import io
import base64
import textwrap
import subprocess

# Gemini AI Configuration
genai.configure(api_key="AIzaSyCjGZozlCwigt4S4Zn7kvuGMXDLyyFEAxI")
model = genai.GenerativeModel('gemini-1.5-flash')
image_model = genai.GenerativeModel('gemini-pro')

def generate_ppt():
    """Generate a PowerPoint presentation from voice input."""
    speak("Please say the topic for your PowerPoint presentation.")
    topic = command()
    
    if not topic:
        speak("No topic detected. Please try again.")
        return

    speak(f"Generating a presentation on {topic}. Please wait.")
    
    try:
        # Generate content using Gemini AI
        prompt = f"Create an educational PowerPoint outline on {topic}. Include a title slide and 4-5 key slides with summarized points."
        response = model.generate_content(prompt)
        slides_content = response.text.split("\n\n")  # Split text into slides

        # Create PowerPoint
        ppt = Presentation()

        # Title Slide
        slide_layout = ppt.slide_layouts[0]
        slide = ppt.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"{topic}"
        subtitle.text = "Generated by Jarvis AI"

        # Add Content Slides
        for slide_text in slides_content:
            slide_layout = ppt.slide_layouts[1]  # Title & Content Layout
            slide = ppt.slides.add_slide(slide_layout)
            title, content = slide.shapes.title, slide.placeholders[1]

            slide_parts = slide_text.split(": ", 1)
            if len(slide_parts) == 2:
                title.text, content.text = slide_parts
            else:
                title.text, content.text = topic, slide_text

        # Save the presentation
        ppt_filename = f"{topic.replace(' ', '_')}.pptx"
        ppt.save(ppt_filename)

        speak(f"Presentation on {topic} has been created successfully. Opening the file now.")
        os.startfile(ppt_filename)

    except Exception as e:
        speak("I encountered an error while generating the presentation.")
        print("Error:", e)

# Initialize text-to-speech engine
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)
engine.setProperty('rate', 180)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

def load_history():
    try:
        with open("conversation_history.txt", "r") as file:
            return file.read()
    except FileNotFoundError:
        return ""

def save_history(user_input, ai_response):
    with open("conversation_history.txt", "a") as file:
        file.write(f"User: {user_input}\nAI: {ai_response}\n\n")

def clear_history():
    open("conversation_history.txt", "w").close()
    speak("Conversation history has been cleared.")

def command():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        audio = r.listen(source)
    try:
        content = r.recognize_google(audio, language='en-in')
        print("You said:", content)
        return content.lower()
    except Exception:
        speak("Please try again")
        return ""

def gemini_response(query):
    try:
        past_conversation = load_history()
        prompt = f"Previous conversation:\n{past_conversation}\nUser: {query}\nResponse:"
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return "I am sorry, I could not process that."

class JarvisThread(QThread):
    update_signal = QtCore.pyqtSignal(str)

    def run(self):
        speak("Hello, I am Jarvis. How can I help you?")
        while True:
            request = command()
            now = datetime.now()
            send_time_hour = now.hour
            send_time_minute = now.minute + 1
            
            if "stop" in request:
                self.update_signal.emit("Jarvis stopped.")
                break
           
            elif "create a powerpoint" in request:
                generate_ppt()
            
            elif "what's the time" in request:
                t = now.strftime("%H:%M")
                speak("Current time: " + t)
            elif "what's the date" in request:
                t = now.strftime("%d-%m-%Y")
                speak("Current date: " + t)
            elif "new task" in request:
                task = request.replace("new task", "").strip()
                if task:
                    with open("todo.txt", "a") as file:
                        file.write(task + "\n")
                    speak("Task added: " + task)
            elif "introduce yourself"  in request:
               ppt_file = "presentation.pptx"  # Change this to your actual file name
               if os.path.exists(ppt_file):
                    speak(f"SURE let me open this just to make you easy to understand myself ")
                    os.startfile(ppt_file)  # Open the PPT file
                    speak("Hello! I am Jarvis, your personal AI assistant, designed to make your digital experience seamless and efficient. Developed by Viraj Shinde, Vedant Surve, Shwet Kadam, and Saheem Nakhwa, I am here to handle all your PC tasks with just your voice.From opening applications, searching the web, and playing your favorite music to managing task lists and sending WhatsApp messages, I do it all. I also provide real-time updates on weather, stock market trends, and much more. And for intelligent, dynamic conversations, I am powered by Gemini AI, ensuring that no query goes unanswered.Your commands drive my actions, making your workflow smarter and faster. So, what can I do for you today?")
               else:
                    speak("PowerPoint file not found in the code directory.")

            elif "tell my task" in request:
                with open("todo.txt", "r") as file:
                    speak("Today's tasks: " + file.read())
            elif "show my task" in request:
                with open("todo.txt", "r") as file:
                    tasks = file.read()
                    notification.notify(title="Today's Tasks", message=tasks)
            elif "open youtube" in request:
                webbrowser.open("www.youtube.com")
            elif "play " in request:
                song_name = request.replace("jarvis play ", "").strip()
                if song_name:
                    speak(f"Playing {song_name} on YouTube")
                    pwk.playonyt(song_name)
                else:
                     speak("Please specify a song name.")
                     
            
            elif "change tab" in request:
                speak("Sure, chnaging the tab")
                pyautogui.hotkey('alt','tab')
                
            elif "turn off the system" in request:
                speak("Sure sir                         shutting down your system")
                pyautogui.press("super")
                pyautogui.typewrite("shutdown")
                pyautogui.sleep(1)
                pyautogui.press("enter")
                

            elif "open" in request:
                query = request.replace("jarvis open", "").strip()
                speak("opening {query}")
                pyautogui.press("super")
                pyautogui.typewrite(query)
                pyautogui.sleep(1)
                pyautogui.press("enter")
            elif "take screenshot" in request:
                speak("Taking screenshot")
                pyautogui.screenshot("my_screenshot.png")
            elif "wikipedia" in request:
                search_query = request.replace("jarvis search wikipedia about", "").strip()
                result = wikipedia.summary(search_query, sentences=3)
                
                speak("searching wikipedia about {search_query}")
                self.update_signal.emit(result)
                speak(result)
            elif "search google" in request:
                search_query = request.replace("jarvis search google about ", "").strip()
                speak("searching google")
                webbrowser.open(f"https://www.google.com/search?q={search_query}")
            elif "send whatsapp" in request:
                pwk.sendwhatmsg("+91 75070 44999", "Hi, I am sending this message and telling you jarvis .", send_time_hour, send_time_minute)
                speak("Sending message")
            
            elif "show history" in request:
                history = load_history()
                speak("Reading conversation history.")
                speak(history)
            elif "clear history" in request:
                clear_history()
            else:
                response = gemini_response(request)
                self.update_signal.emit(f"You: {request}\nJarvis: {response}")
                speak(response)
                save_history(request, response)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1317, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -60, 1341, 851))
        
        # Use QMovie to display animated GIF
        self.movie = QtGui.QMovie("gui.gif")
        self.label.setMovie(self.movie)
        self.movie.start()
        
        self.label.setScaledContents(True)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(530, 251, 471, 361))
        self.pushButton_2 = QtWidgets.QPushButton("RUN", self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 640, 101, 31))
        self.pushButton_3 = QtWidgets.QPushButton("STOP", self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 640, 101, 31))
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(140, 10, 191, 31))
        self.textBrowser_3.setStyleSheet("background:transparent;")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1070, 10, 191, 31))
        self.textBrowser_4.setStyleSheet("background:transparent;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_2.clicked.connect(self.start_jarvis)
        self.pushButton_3.clicked.connect(self.stop_jarvis)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_time)
        self.timer.start(1000)
        self.jarvis_thread = None
    
    def update_time(self):
        self.textBrowser_3.setText(datetime.now().strftime("%H:%M:%S"))
        self.textBrowser_4.setText(datetime.now().strftime("%d-%m-%Y"))
    
    def start_jarvis(self):
        self.textBrowser_2.append("Jarvis started...")
        self.jarvis_thread = JarvisThread()
        self.jarvis_thread.update_signal.connect(self.textBrowser_2.append)
        self.jarvis_thread.start()
    
    def stop_jarvis(self):
        if self.jarvis_thread:
            self.jarvis_thread.terminate()
        speak("Shutting down")
        QtWidgets.qApp.quit()

class MovableMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MovableMainWindow, self).__init__()
        self.oldPos = None
    
    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def mouseMoveEvent(self, event):
        if self.oldPos:
            delta = QtCore.QPoint(event.globalPos() - self.oldPos)
            self.move(self.x() + delta.x(), self.y() + delta.y())
            self.oldPos = event.globalPos()

class FaceRecognitionThread(QThread):
    update_frame = QtCore.pyqtSignal(QImage)
    authentication_result = QtCore.pyqtSignal(bool)
    
    def __init__(self, reference_image_path):
        super().__init__()
        self.reference_image_path = reference_image_path
        self.running = True
        
    def run(self):
        # Load face cascade for simple face detection - no dlib required
        face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
        
        # Access webcam (use camera index 1 for DroidCam)
        cap = cv2.VideoCapture(1)  # Changed from 0 to 1 for DroidCam
        if not cap.isOpened():
            print("Cannot open camera")
            self.authentication_result.emit(False)
            return
            
        face_detected_frames = 0
        required_frames = 20  # Need to detect face in 20 frames to authenticate
        attempts = 0
        max_attempts = 100  # About 10 seconds of trying
        
        while self.running and attempts < max_attempts:
            ret, frame = cap.read()
            if not ret:
                print("Can't receive frame. Exiting...")
                break
                
            # Convert to grayscale for face detection
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            
            # Detect faces
            faces = face_cascade.detectMultiScale(gray, 1.3, 5)
            
            # Add visual effects to frame
            # Add a border
            frame = cv2.copyMakeBorder(frame, 10, 10, 10, 10, cv2.BORDER_CONSTANT, value=[0, 120, 255])
            
            # Add scanning effect overlay
            overlay = frame.copy()
            # Draw horizontal scan line
            scan_position = (attempts % 50) * (frame.shape[0] // 50)
            cv2.line(overlay, (0, scan_position), (frame.shape[1], scan_position), (0, 255, 0), 2)
            frame = cv2.addWeighted(overlay, 0.7, frame, 0.3, 0)
            
            # Add system status text
            cv2.putText(frame, "JARVIS SECURITY SYSTEM", (frame.shape[1]//2 - 150, 30), 
                      cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
            
            if len(faces) > 0:
                # Face detected
                face_detected_frames += 1
                
                # Draw rectangle around face
                for (x, y, w, h) in faces:
                    # Draw fancy rectangle
                    cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
                    
                    # Draw corner lines for futuristic look
                    corner_length = 20
                    # Top left
                    cv2.line(frame, (x, y), (x + corner_length, y), (0, 255, 255), 2)
                    cv2.line(frame, (x, y), (x, y + corner_length), (0, 255, 255), 2)
                    # Top right
                    cv2.line(frame, (x+w, y), (x+w - corner_length, y), (0, 255, 255), 2)
                    cv2.line(frame, (x+w, y), (x+w, y + corner_length), (0, 255, 255), 2)
                    # Bottom left
                    cv2.line(frame, (x, y+h), (x + corner_length, y+h), (0, 255, 255), 2)
                    cv2.line(frame, (x, y+h), (x, y+h - corner_length), (0, 255, 255), 2)
                    # Bottom right
                    cv2.line(frame, (x+w, y+h), (x+w - corner_length, y+h), (0, 255, 255), 2)
                    cv2.line(frame, (x+w, y+h), (x+w, y+h - corner_length), (0, 255, 255), 2)
                    
                    progress = min(face_detected_frames / required_frames, 1.0)
                    bar_width = int(w * progress)
                    
                    # Draw progress bar
                    cv2.rectangle(frame, (x, y+h+5), (x+bar_width, y+h+15), (0, 255, 0), -1)
                    cv2.rectangle(frame, (x, y+h+5), (x+w, y+h+15), (255, 255, 255), 1)
                    
                    # Progress percentage
                    percentage = int(progress * 100)
                    cv2.putText(frame, f"Scanning: {percentage}%", (x, y+h+30), 
                              cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                
                # Check if we have enough consistent detections
                if face_detected_frames >= required_frames:
                    # Authentication successful
                    # Create success overlay
                    success_overlay = frame.copy()
                    cv2.rectangle(success_overlay, (0, 0), (frame.shape[1], frame.shape[0]), (0, 255, 0), -1)
                    
                    # Blend with original frame
                    frame = cv2.addWeighted(success_overlay, 0.3, frame, 0.7, 0)
                    
                    # Add success text
                    cv2.putText(frame, "ACCESS GRANTED", (frame.shape[1]//2 - 150, frame.shape[0]//2), 
                              cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 3)
                    cv2.putText(frame, "AUTHENTICATION SUCCESSFUL", (frame.shape[1]//2 - 200, frame.shape[0]//2 + 50), 
                              cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
                    
                    # Convert frame to QImage and emit
                    h, w, ch = frame.shape
                    qt_image = QImage(frame.data, w, h, ch * w, QImage.Format_RGB888)
                    self.update_frame.emit(qt_image.rgbSwapped())
                    
                    # Wait a moment to display the success message
                    time.sleep(1.5)
                    
                    # Authentication successful - speak confirmation
                    speak("Authentication successful. Welcome back, sir.")
                    
                    # Authentication successful
                    cap.release()
                    self.authentication_result.emit(True)
                    return
            else:
                # Reset counter if face is lost
                face_detected_frames = max(0, face_detected_frames - 1)
                # Warning text
                cv2.putText(frame, "No face detected", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
                cv2.putText(frame, "Please position your face in the camera view", (50, 80), 
                          cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
            
            # Add scanning line effect
            
            # Convert frame to QImage and emit
            h, w, ch = frame.shape
            qt_image = QImage(frame.data, w, h, ch * w, QImage.Format_RGB888)
            self.update_frame.emit(qt_image.rgbSwapped())
            
            attempts += 1
            time.sleep(0.1)
            
        # If we get here without successful authentication
        cap.release()
        speak("Authentication failed. Access denied.")
        self.authentication_result.emit(False)
    
    def stop(self):
        self.running = False
        self.wait()

class FaceAuthenticationWindow(QtWidgets.QMainWindow):
    def __init__(self, reference_image_path="face_reference.jpg"):
        super().__init__()
        self.reference_image_path = reference_image_path
        self.initUI()
        
    def initUI(self):
        self.setWindowTitle('JARVIS Security System')
        self.setGeometry(100, 100, 800, 600)
        self.setStyleSheet("background-color: #1E1E1E;")
        
        # Set window icon
        self.setWindowIcon(QtGui.QIcon("jarvis_icon.png"))
        
        # Central widget
        central_widget = QtWidgets.QWidget()
        self.setCentralWidget(central_widget)
        
        # Main layout
        main_layout = QtWidgets.QVBoxLayout(central_widget)
        main_layout.setContentsMargins(20, 20, 20, 20)
        
        # Title label
        title_label = QtWidgets.QLabel("JARVIS SECURITY AUTHENTICATION")
        title_label.setAlignment(QtCore.Qt.AlignCenter)
        title_label.setStyleSheet("color: #00A9F4; font-size: 24px; font-weight: bold; margin-bottom: 10px;")
        main_layout.addWidget(title_label)
        
        # Video frame with border
        video_frame = QtWidgets.QFrame()
        video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        video_frame.setStyleSheet("border: 2px solid #00A9F4; border-radius: 10px; padding: 5px; background-color: #2D2D30;")
        video_layout = QtWidgets.QVBoxLayout(video_frame)
        
        # Video display label
        self.video_label = QtWidgets.QLabel()
        self.video_label.setMinimumSize(700, 450)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setStyleSheet("border: none;")
        video_layout.addWidget(self.video_label)
        
        main_layout.addWidget(video_frame)
        
        # Status label
        self.status_label = QtWidgets.QLabel("Initializing facial recognition system...")
        self.status_label.setStyleSheet("font-size: 18px; color: #00A9F4; margin-top: 10px;")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(self.status_label)
        
        # Start face recognition with voice prompt
        speak("Initializing security systems")
        QTimer.singleShot(1500, self.start_face_recognition)
    
    def start_face_recognition(self):
        speak("Beginning facial authentication")
        self.status_label.setText("Looking for your face...")
        # Create and start the face recognition thread
        self.face_thread = FaceRecognitionThread(self.reference_image_path)
        self.face_thread.update_frame.connect(self.update_frame)
        self.face_thread.authentication_result.connect(self.handle_authentication)
        self.face_thread.start()
    
    def update_frame(self, qt_image):
        pixmap = QPixmap.fromImage(qt_image)
        self.video_label.setPixmap(pixmap.scaled(self.video_label.width(), self.video_label.height(), QtCore.Qt.KeepAspectRatio))
    
    def handle_authentication(self, success):
        if success:
            self.status_label.setText("Authentication Successful! Launching JARVIS...")
            self.status_label.setStyleSheet("font-size: 18px; color: #00FF00; margin-top: 10px;")
            # Wait a moment to display the success message
            QTimer.singleShot(2000, self.launch_jarvis)
        else:
            self.status_label.setText("Authentication Failed! Access Denied.")
            self.status_label.setStyleSheet("font-size: 18px; color: #FF0000; margin-top: 10px;")
            # Wait a moment and then close the application
            QTimer.singleShot(3000, self.close)
    
    def launch_jarvis(self):
        # Close the authentication window
        self.close()
        # Launch the Jarvis application
        subprocess.Popen(["python", "final copy 2.py"])
    
    def closeEvent(self, event):
        # Stop the face recognition thread when closing the window
        if hasattr(self, 'face_thread'):
            self.face_thread.stop()
        event.accept()

def save_reference_image():
    """Capture and save a reference image of the user's face"""
    if os.path.exists("face_reference.jpg"):
        return  # Reference image already exists
        
    print("Capturing reference image of your face...")
    cap = cv2.VideoCapture(1)  # Changed from 0 to 1 for DroidCam
    if not cap.isOpened():
        print("Cannot open camera")
        return False
        
    # Wait a bit to let the camera adjust
    for _ in range(10):
        cap.read()
        time.sleep(0.1)
    
    ret, frame = cap.read()
    cap.release()
    
    if ret:
        # Save the reference image
        cv2.imwrite("face_reference.jpg", frame)
        print("Reference image saved as 'face_reference.jpg'")
        return True
    else:
        print("Failed to capture reference image")
        return False

if __name__ == "__main__":
    # Check if running in test mode (without camera)
    if len(sys.argv) > 1 and sys.argv[1] == "--no-camera":
        print("Running in test mode - bypassing face authentication")
        # Launch Jarvis directly
        subprocess.Popen(["python", "final copy 2.py"])
        sys.exit()
        
    # Check if reference image exists, otherwise create one
    if not os.path.exists("face_reference.jpg"):
        # If no reference image, capture one
        app = QtWidgets.QApplication(sys.argv)
        msgBox = QtWidgets.QMessageBox()
        msgBox.setWindowTitle("First Time Setup")
        msgBox.setText("No reference face image found. Would you like to capture one now? (Or run with --no-camera flag to bypass)")
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        msgBox.setDefaultButton(QtWidgets.QMessageBox.Yes)
        
        if msgBox.exec_() == QtWidgets.QMessageBox.Yes:
            save_reference_image()
        else:
            sys.exit()
    
    # Start the authentication app
    app = QtWidgets.QApplication(sys.argv)
    window = FaceAuthenticationWindow()
    window.show()
    sys.exit(app.exec_())