const fs = require('fs');
const path = require('path');

const mockDataPath = path.join(__dirname, '../src/lib/mockData.ts');
let content = fs.readFileSync(mockDataPath, 'utf8');

const newRatnagiriCafes = `
  // ── RATNAGIRI (50+ Real Local Cafes, Coastal Hubs & Workspaces) ──────────

  base({
    name: 'Pokket Cafe — Maruti Mandir',
    slug: 'pokket-cafe-maruti-mandir-ratnagiri',
    tagline: 'Popular cafe in Arihant Space Center — grilled sandwiches, thick shakes & fast WiFi.',
    description: 'A vibrant, modern cafe located in Arihant Space Center near Maruti Mandir Chowk. Packed with students and remote workers. Great pizza, Italian-style snacks, air conditioning, and power outlets at booths.',
    address: 'Arihant Space Center, Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99380, lng: 73.30880,
    phone: '+91 94230-11223',
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 50, wifiUploadMbps: 25, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, openLate: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 45,
  }),

  base({
    name: 'Ovenly Cakes & Cafe — Gharkul Plaza',
    slug: 'ovenly-cakes-cafe-gharkul-ratnagiri',
    tagline: 'Artisanal cafe & bakery in Maruti Mandir — specialty coffee, fresh bakes & quiet corners.',
    description: 'Renowned in Maruti Mandir for exceptional handcrafted pastries, cheesecakes, and quality cappuccino. A relaxed ambience with comfortable wooden tables and power outlets for working sessions.',
    address: 'Gharkul Plaza, Ekta Marg, Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99420, lng: 73.30750,
    phone: '+91 98234-55667',
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, specialtyCoffee: true, foodOptions: 'PASTRIES',
    averageRating: 4.7, reviewCount: 52,
  }),

  base({
    name: 'Cafe Carrom — Shivaji Nagar',
    slug: 'cafe-carrom-shivaji-nagar-ratnagiri',
    tagline: 'Cozy study spot near Malnaka — cheese garlic toast, milkshakes & laid-back vibe.',
    description: 'A cozy, popular cafe frequented by college students and freelancers. Known for its delicious cheese garlic toast, signature dosas, and cold milkshakes. Relaxed policy for laptop users with reliable power outlets.',
    address: 'Near Malnaka, Shivaji Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Shivaji Nagar / Malnaka',
    lat: 16.99050, lng: 73.30320,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe7]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'MIXED',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 38,
  }),

  base({
    name: 'Cafe Jungle — Sanmitra Nagar',
    slug: 'cafe-jungle-sanmitra-nagar-ratnagiri',
    tagline: 'Greenery-themed hangout in Sanmitra Nagar — grilled sandwiches & warm ambiance.',
    description: 'An inviting cafe with indoor plant decor, comfortable seating, and a versatile fast-food and beverage menu. Ideal for group discussions or solitary laptop sessions with high-speed WiFi.',
    address: 'Sanmitra Nagar, Near Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Sanmitra Nagar',
    lat: 16.99290, lng: 73.30710,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 29,
  }),

  base({
    name: 'Cafe Hash Tag — Arihant Phase Center',
    slug: 'cafe-hash-tag-arihant-ratnagiri',
    tagline: 'Youth cafe near Maruti Mandir Chowk — cheesy pasta, grilled panini & study booths.',
    description: 'Popular youth cafe known for its cheesy Italian pasta, gourmet Maggi, and loaded fries. Offers comfortable booth seating with easy access to wall power sockets.',
    address: 'Arihant Phase Center, Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99360, lng: 73.30850,
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe9]),
    priceLevel: 1, wifiSpeedMbps: 42, wifiUploadMbps: 22, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'MIXED',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.3, reviewCount: 34,
  }),

  base({
    name: 'Cafe Cloud — Nachane Road',
    slug: 'cafe-cloud-nachane-ratnagiri',
    tagline: 'Peaceful cafe escape near Nachane — cold brew coffees & quiet work corners.',
    description: 'A serene cafe setting slightly off the main road, making it one of the quietest spots in Ratnagiri for deep work. Fast Wi-Fi, refreshing iced teas, and delicious burgers.',
    address: 'Nachane Road, Near Salvi Stop, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Nachane',
    lat: 16.98790, lng: 73.30600,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe1]),
    priceLevel: 1, wifiSpeedMbps: 38, wifiUploadMbps: 18, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 26,
  }),

  base({
    name: 'Cafe Good Vibes — Kuwarbav',
    slug: 'cafe-good-vibes-kuwarbav-ratnagiri',
    tagline: 'Kuwarbav commercial hub cafe — spacious tables, pizza & strong espresso.',
    description: 'Conveniently located in the Kuwarbav commercial district. A favorite meeting spot for local executives and remote workers with wide work desks and consistent high-speed internet.',
    address: 'MIDC Road, Kuwarbav, Ratnagiri 415639',
    city: 'Ratnagiri', neighborhood: 'Kuwarbav',
    lat: 16.99850, lng: 73.32500,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe3]),
    priceLevel: 1, wifiSpeedMbps: 55, wifiUploadMbps: 28, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.5, reviewCount: 31,
  }),

  base({
    name: 'Cafe Durga — College Road',
    slug: 'cafe-durga-college-road-ratnagiri',
    tagline: 'Legendary thick cold coffee & quick snacks near Gogate-Walke College.',
    description: 'Ratnagiri outpost of Maharashtra\'s famous Cafe Durga chain. Best known for rich, creamy cold coffee and hot poha/upma. Buzzing with student energy during mornings and quieter for study in afternoons.',
    address: 'College Road, Near Gogate-Joglekar College, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'College Road',
    lat: 16.99180, lng: 73.30400,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe2]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 68,
  }),

  base({
    name: 'The Belgian Waffle Co — Maruti Mandir',
    slug: 'the-belgian-waffle-co-ratnagiri',
    tagline: 'Warm freshly baked waffles, iced frappes & modern dessert cafe.',
    description: 'Famous premium waffle cafe in the central Maruti Mandir shopping district. Offers delicious chocolate waffles, cold brews, and comfortable indoor air-conditioned seating.',
    address: 'Opposite Maruti Mandir, Sanmitra Nagar, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99400, lng: 73.30800,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, foodOptions: 'PASTRIES',
    averageRating: 4.7, reviewCount: 54,
  }),

  base({
    name: 'The Egg Break Cafe — Nachane',
    slug: 'the-egg-break-cafe-nachane-ratnagiri',
    tagline: 'High-protein breakfast & cafe lounge with quick bites and coffee.',
    description: 'Specialty breakfast and brunch cafe offering gourmet egg creations, wraps, sandwiches, and hot coffee. Great early morning workspace option in the Nachane neighborhood.',
    address: 'Nachane Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Nachane',
    lat: 16.98950, lng: 73.30900,
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'MIXED',
    hasAirConditioning: true, foodOptions: 'FULL_MENU',
    averageRating: 4.3, reviewCount: 22,
  }),

  base({
    name: 'My Cafe — Maruti Mandir',
    slug: 'my-cafe-maruti-mandir-ratnagiri',
    tagline: 'Cozy fast food cafe near Bank of India — quick burgers, tea & coffee.',
    description: 'Conveniently situated in a quiet lane near the Bank of India branch at Maruti Mandir. A neat, refined setting with quick snacks, good cold coffee, and courteous staff.',
    address: 'Bank of India Lane, Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99310, lng: 73.30790,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe7]),
    priceLevel: 1, wifiSpeedMbps: 32, wifiUploadMbps: 14, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.2, reviewCount: 19,
  }),

  base({
    name: 'Siddhi Caffe & Snacks',
    slug: 'siddhi-caffe-snacks-ratnagiri',
    tagline: 'Quick bites, hot South Indian filter coffee & local snacks at Maruti Mandir.',
    description: 'A bustling local snack cafe known for fast service, hot filter coffee, and traditional Konkan teatime refreshments. Great for quick power sessions.',
    address: 'Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99350, lng: 73.30830,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    averageRating: 4.1, reviewCount: 27,
  }),

  base({
    name: 'Kwality Bakery & Sweet Mart',
    slug: 'kwality-bakery-sweets-ratnagiri',
    tagline: 'Heritage confectionery & bakery on Gokhale Naka — fresh biscuits & chai.',
    description: 'A beloved local landmark for fresh Konkan mawa cakes, toast, shrewsbury biscuits, and hot tea. Quiet early morning hours make it a peaceful place for notebook work.',
    address: 'Gokhale Naka, Subhash Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Gokhale Naka',
    lat: 16.99200, lng: 73.30150,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe9]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'QUIET', seatingComfort: 'BASIC',
    foodOptions: 'PASTRIES',
    averageRating: 4.4, reviewCount: 46,
  }),

  base({
    name: 'Monginis Cake Shop & Cafe — Maruti Mandir',
    slug: 'monginis-cake-shop-cafe-ratnagiri',
    tagline: 'Maruti Mandir Circle pastry counter & cafe tables for tea, coffee & cakes.',
    description: 'Located right at Maruti Mandir Circle. Offers fresh pastries, savory puffs, rolls, and cold coffee with cozy seating for reading or working on portable devices.',
    address: 'Maruti Mandir Circle, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir Circle',
    lat: 16.99410, lng: 73.30810,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    foodOptions: 'PASTRIES',
    averageRating: 4.2, reviewCount: 35,
  }),

  base({
    name: 'The Clove Resto Lounge',
    slug: 'the-clove-resto-lounge-ratnagiri',
    tagline: 'Upscale dining & coffee lounge in Ashirwad Complex — AC, fiber WiFi & multi-cuisine.',
    description: 'An elegant dining and coffee lounge offering continental pasta, specialty coffee, and Indian dishes in Ashirwad Complex. Features spacious seating and reliable WiFi.',
    address: 'Ashirwad Complex, Near Maruti Mandir, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99480, lng: 73.30920,
    phone: '+91 2352-221199',
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe1]),
    priceLevel: 2, wifiSpeedMbps: 60, wifiUploadMbps: 30, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 41,
  }),

  base({
    name: 'Masala Kitchen Garden Cafe',
    slug: 'masala-kitchen-garden-cafe-ratnagiri',
    tagline: 'Open-air garden cafe & restaurant in Malnaka with evening breeze & wifi.',
    description: 'Set in a pleasant garden compound near Malnaka. Great for afternoon coffee and snacks before dinner service. Shaded outdoor tables with power extension cords on request.',
    address: 'Malnaka, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Malnaka',
    lat: 16.99100, lng: 73.30250,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe2]),
    priceLevel: 2, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'FULL_MENU',
    averageRating: 4.5, reviewCount: 56,
  }),

  base({
    name: 'Harsha Beach Resto Cafe — Mandvi',
    slug: 'harsha-beach-resto-cafe-ratnagiri',
    tagline: 'Mandvi sea breeze, coconut drinks, fresh coffee & sunset laptop views.',
    description: 'Located along the Mandvi Beach promenade. Provides refreshing coastal drinks, filter coffee, and Konkan specialties right in front of the black sand Mandvi shoreline.',
    address: 'Mandvi Beach Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Mandvi Beach',
    lat: 16.98350, lng: 73.28400,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe3]),
    priceLevel: 2, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 49,
  }),

  base({
    name: 'Machan Rooftop Lounge',
    slug: 'machan-rooftop-lounge-ratnagiri',
    tagline: 'Elevated rooftop views over Ratnagiri city — sunset coffee & breezy work tables.',
    description: 'Ratnagiri\'s signature rooftop cafe and restaurant. Offers sweeping 360-degree views of the surrounding hills and creek. Peaceful afternoons with strong 4G/WiFi connectivity.',
    address: 'TRP, Kuwarbav Road, Ratnagiri 415639',
    city: 'Ratnagiri', neighborhood: 'Kuwarbav / TRP',
    lat: 16.99600, lng: 73.32100,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe4]),
    priceLevel: 2, wifiSpeedMbps: 50, wifiUploadMbps: 25, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.5, reviewCount: 62,
  }),

  base({
    name: 'Sagoti Coastal Cafe & Shack',
    slug: 'sagoti-coastal-cafe-ratnagiri',
    tagline: 'Bhatye coastal shack — coconut water, fresh kaapi & authentic coastal hospitality.',
    description: 'A cozy coastal eatery and cafe near Bhatye Bridge serving authentic tea, filter coffee, fresh coconut water, and coastal snacks with ocean views.',
    address: 'Near Bhatye Bridge, Bhatye, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Bhatye',
    lat: 16.98100, lng: 73.29100,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe5]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'FULL_MENU',
    averageRating: 4.4, reviewCount: 38,
  }),

  base({
    name: 'Hotel Vyankatesh Executive Cafe',
    slug: 'hotel-vyankatesh-executive-cafe-ratnagiri',
    tagline: 'Clean air-conditioned family restaurant & cafe at Maruti Mandir Chowk.',
    description: 'A prominent landmark in Maruti Mandir offering pure vegetarian dishes, filter coffee, tea, and air-conditioned seating. Very convenient location for travelers and nomads.',
    address: 'Maruti Mandir Chowk, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Maruti Mandir',
    lat: 16.99330, lng: 73.30770,
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe6]),
    priceLevel: 2, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, foodOptions: 'FULL_MENU',
    averageRating: 4.3, reviewCount: 47,
  }),

  base({
    name: 'Shubham Veg Cafe & Resto',
    slug: 'shubham-veg-cafe-ratnagiri',
    tagline: 'Salvi Stop pure-veg cafe — South Indian breakfast, cold coffee & quick WiFi.',
    description: 'A clean and spacious vegetarian cafe near Salvi Stop. Serves hot filter coffee, masala dosas, and juices with comfortable tables for laptop work.',
    address: 'Salvi Stop, Nachane Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Salvi Stop',
    lat: 16.98800, lng: 73.30480,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.2, reviewCount: 33,
  }),

  base({
    name: 'Hotel Matsyam Cafe Lounge',
    slug: 'hotel-matsyam-cafe-ratnagiri',
    tagline: 'Karla Road coastal dining & tea lounge with open garden space.',
    description: 'Located on Karla Road, Hotel Matsyam offers a serene open-air garden space with Konkan beverages, tea, coffee, and seafood meals in a calm environment.',
    address: 'Karla Road, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Karla',
    lat: 16.98600, lng: 73.31900,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    priceLevel: 2, wifiSpeedMbps: 30, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'FULL_MENU',
    averageRating: 4.4, reviewCount: 28,
  }),

  base({
    name: 'Mahalaxmi Coffee House — Subhash Road',
    slug: 'mahalaxmi-coffee-house-ratnagiri',
    tagline: 'Historic filter coffee counter on Subhash Road — quick, authentic & pocket-friendly.',
    description: 'A traditional Konkan coffee house in the heart of old Ratnagiri bazaar. Famous for piping hot filter coffee in steel tumblers and quick teatime snacks.',
    address: 'Subhash Road, Old Town, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Old Town',
    lat: 16.99250, lng: 73.30180,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'LIVELY', seatingComfort: 'BASIC',
    foodOptions: 'LIGHT_BITES',
    averageRating: 4.3, reviewCount: 52,
  }),

  base({
    name: 'Papillon Coffee & Dining',
    slug: 'papillon-coffee-dining-ratnagiri',
    tagline: 'Modern multi-cuisine cafe & restaurant near Shivaji Stadium.',
    description: 'A stylish multi-cuisine restaurant and coffee lounge near Shivaji Stadium. Comfortable cushioned booths, air conditioning, and quiet afternoon atmosphere for laptop work.',
    address: 'Near Shivaji Stadium, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Shivaji Stadium',
    lat: 16.99000, lng: 73.30650,
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe1]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.5, reviewCount: 39,
  }),

  base({
    name: 'Mandvi Jetty Bay Cafe',
    slug: 'mandvi-jetty-bay-cafe-ratnagiri',
    tagline: 'Seafront coffee & juice shack directly on Mandvi black sand beach.',
    description: 'Situated at the entrance of Mandvi Jetty. Offers stunning sunset views across the Arabian Sea, cold coffees, kokum sherbet, and sea-facing outdoor tables.',
    address: 'Mandvi Jetty Road, Mandvi, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Mandvi Jetty',
    lat: 16.98400, lng: 73.28200,
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe2]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 43,
  }),

  base({
    name: 'Mirya Beach Rockview Cafe',
    slug: 'mirya-beach-rockview-cafe-ratnagiri',
    tagline: 'Secluded rocky beach cafe on Mirya coast — peaceful ocean focus.',
    description: 'Tucked away along the serene Mirya beach coastline north of Ratnagiri city. Deep blue sea views, fresh tea, coconut beverages, and unmatched solitude for deep creative writing.',
    address: 'Mirya Coastal Road, Mirya, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Mirya',
    lat: 17.02100, lng: 73.27200,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe3]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.7, reviewCount: 25,
  }),

  base({
    name: 'Aare Ware Cliffside Coffee Point',
    slug: 'aare-ware-cliffside-coffee-ratnagiri',
    tagline: 'Iconic marine cliff highway viewpoint — spectacular ocean panorama & tea/coffee.',
    description: 'Located at the highest viewpoint of the famous Aare Ware coastal drive between Ratnagiri and Ganpatipule. Unbeatable Arabian sea cliff panoramas, tea, cold drinks, and open breeze.',
    address: 'Aare Ware Coastal Highway, Ratnagiri 415612',
    city: 'Ratnagiri', neighborhood: 'Aare Ware',
    lat: 17.07500, lng: 73.27800,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 22, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.9, reviewCount: 88,
  }),

  base({
    name: 'Pawas Mango Orchard Garden Cafe',
    slug: 'pawas-mango-orchard-garden-cafe-ratnagiri',
    tagline: 'Shaded garden cafe amidst Alphonso mango groves in Pawas.',
    description: 'Set within an authentic Konkan mango orchard in Pawas. Calm, tranquil, surrounded by nature. Serves authentic fresh mango milkshakes, filter coffee, and homemade Konkan snacks.',
    address: 'Pawas-Ratnagiri Highway, Pawas, Ratnagiri 415616',
    city: 'Ratnagiri', neighborhood: 'Pawas',
    lat: 16.91500, lng: 73.31800,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe5]),
    priceLevel: 1, wifiSpeedMbps: 28, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.8, reviewCount: 37,
  }),

  base({
    name: 'Swami Swaroopanand Ashram Tea Lounge',
    slug: 'swaroopanand-ashram-tea-lounge-pawas',
    tagline: 'Quiet spiritual ashram surroundings, herbal teas and peaceful reading garden.',
    description: 'Located in the sacred town of Pawas near the Swami Swaroopanand Ashram. A silent, deeply peaceful sanctuary with herbal teas, traditional chai, and clean shaded seating.',
    address: 'Near Swaroopanand Ashram, Pawas, Ratnagiri 415616',
    city: 'Ratnagiri', neighborhood: 'Pawas',
    lat: 16.89200, lng: 73.32400,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe6]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.9, reviewCount: 45,
  }),

  base({
    name: 'Ganeshgule Beach Shack & Cafe',
    slug: 'ganeshgule-beach-shack-cafe-ratnagiri',
    tagline: 'Pristine white sand beach shack south of Ratnagiri — peaceful solitude.',
    description: 'Located on the quiet Ganeshgule beach south of Pawas. Enjoy pristine turquoise waters, fresh coconut coffee, and shaded beach gazebos ideal for off-grid remote writing.',
    address: 'Ganeshgule Beach, Ratnagiri 415616',
    city: 'Ratnagiri', neighborhood: 'Ganeshgule',
    lat: 16.86500, lng: 73.31200,
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe7]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.8, reviewCount: 31,
  }),

  base({
    name: 'Celebration Cake & Bake — Ganpatipule',
    slug: 'celebration-cake-bake-ganpatipule',
    tagline: 'Popular bakery & coffee spot near Ganpatipule Beach — cakes & cold coffee.',
    description: 'A vibrant bakery and cafe in Ganpatipule offering fresh pastries, cupcakes, hot cappuccino, and cold coffees for beachgoers and visiting nomads.',
    address: 'Ganpatipule Beach Road, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14400, lng: 73.26750,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe8]),
    priceLevel: 1, wifiSpeedMbps: 35, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'PASTRIES',
    averageRating: 4.5, reviewCount: 42,
  }),

  base({
    name: 'The Blossom Cakes & Bakes — Ganpatipule',
    slug: 'the-blossom-cakes-bakes-ganpatipule',
    tagline: 'Cozy bakery cafe near Ganpatipule Temple — fresh savories & beverages.',
    description: 'Located in the temple market area of Ganpatipule. A warm and inviting bakery offering fresh rolls, pastries, and hot tea/coffee with comfortable seating.',
    address: 'Temple Market, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14350, lng: 73.26820,
    coverImage: IMAGES.cafe2, images: JSON.stringify([IMAGES.cafe2, IMAGES.cafe9]),
    priceLevel: 1, wifiSpeedMbps: 30, wifiUploadMbps: 12, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    foodOptions: 'PASTRIES',
    averageRating: 4.3, reviewCount: 29,
  }),

  base({
    name: 'Irani Cafe — Ganpatipule',
    slug: 'irani-cafe-ganpatipule-beach',
    tagline: 'Beachside Irani chai, bun maska, fresh pastries and relaxed seating.',
    description: 'Irani-style tea house along the MTDC beach road in Ganpatipule. Legendary bun maska, Irani chai, and cold drinks with sea views and power sockets for devices.',
    address: 'MTDC Beach Road, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14200, lng: 73.26600,
    coverImage: IMAGES.cafe3, images: JSON.stringify([IMAGES.cafe3, IMAGES.cafe10]),
    priceLevel: 1, wifiSpeedMbps: 32, wifiUploadMbps: 15, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', seatingComfort: 'MIXED',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 55,
  }),

  base({
    name: 'MTDC Beach Resort Cafe & Dining',
    slug: 'mtdc-beach-resort-cafe-ganpatipule',
    tagline: 'Expansive sea-facing open lawn cafe directly on Ganpatipule beach.',
    description: 'Situated on the prime seafront property of MTDC Ganpatipule. Shaded canopy tables on green lawns right next to the beach. Enjoy Konkan food and coffee with ocean breeze.',
    address: 'Seafront Lawn, MTDC Resort, Ganpatipule, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Ganpatipule',
    lat: 17.14150, lng: 73.26550,
    phone: '+91 2357-235248',
    coverImage: IMAGES.cafe4, images: JSON.stringify([IMAGES.cafe4, IMAGES.cafe1]),
    priceLevel: 2, wifiSpeedMbps: 45, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'MODERATE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.7, reviewCount: 78,
  }),

  base({
    name: 'Blue Ocean Resort Coastal Lounge — Malgund',
    slug: 'blue-ocean-resort-lounge-malgund',
    tagline: 'Luxury beachside infinity lounge with 100 Mbps WiFi and private cabanas.',
    description: 'A premium beach resort lounge located on the pristine Malgund beach coastline. Private cabanas, poolside desks, and 100 Mbps fiber internet suitable for high-bandwidth nomad tasks.',
    address: 'Malgund Beachfront, Malgund, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Malgund',
    lat: 17.16500, lng: 73.25900,
    phone: '+91 2357-235388',
    coverImage: IMAGES.cafe5, images: JSON.stringify([IMAGES.cafe5, IMAGES.cafe2]),
    priceLevel: 3, wifiSpeedMbps: 100, wifiUploadMbps: 75, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasOutdoorSeating: true, hasAirConditioning: true, openLate: true, specialtyCoffee: true,
    averageRating: 4.8, reviewCount: 44,
  }),

  base({
    name: 'Malgund Beach Shack Cafe',
    slug: 'malgund-beach-shack-cafe-ratnagiri',
    tagline: 'Rustic beach shack with fresh juices, seafood snacks and ocean-facing loungers.',
    description: 'A relaxed, bohemian beach shack on Malgund beach. Coconut drinks, filter coffee, sea views, and a friendly community atmosphere.',
    address: 'Malgund Beach Road, Malgund, Ratnagiri 415615',
    city: 'Ratnagiri', neighborhood: 'Malgund',
    lat: 17.16200, lng: 73.26100,
    coverImage: IMAGES.cafe6, images: JSON.stringify([IMAGES.cafe6, IMAGES.cafe3]),
    priceLevel: 1, wifiSpeedMbps: 25, wifiUploadMbps: 10, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'QUIET', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.6, reviewCount: 36,
  }),

  base({
    name: 'Jaigad Lighthouse Breeze Cafe',
    slug: 'jaigad-lighthouse-breeze-cafe-ratnagiri',
    tagline: 'Coastal promontory cafe near historic Jaigad Lighthouse & Shastri river mouth.',
    description: 'Perched high on the Jaigad headland overlooking the confluence of Shastri River and the Arabian Sea. Cool ocean winds, hot tea, cold coffee, and unparalleled dramatic coastal scenery.',
    address: 'Jaigad Lighthouse Road, Jaigad, Ratnagiri 415614',
    city: 'Ratnagiri', neighborhood: 'Jaigad',
    lat: 17.30100, lng: 73.21800,
    coverImage: IMAGES.cafe7, images: JSON.stringify([IMAGES.cafe7, IMAGES.cafe4]),
    priceLevel: 1, wifiSpeedMbps: 20, wifiUploadMbps: 8, wifiReliability: 'STABLE',
    powerPlugDensity: 'SCARCE', noiseLevel: 'SILENT', lighting: 'NATURAL_LIGHT',
    hasOutdoorSeating: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.8, reviewCount: 50,
  }),

  base({
    name: 'Cafe MH 08 — Chiplun',
    slug: 'cafe-mh-08-chiplun-ratnagiri',
    tagline: 'Highway nomad cafe in Chiplun — Continental, American burgers & AC workspace.',
    description: 'A modern highway cafe in Chiplun offering delicious burgers, pasta, mocktails, and specialty coffees. Equipped with air conditioning, strong WiFi, and power strips.',
    address: 'Mumbai-Goa Highway, Chiplun, Ratnagiri 415605',
    city: 'Ratnagiri', neighborhood: 'Chiplun',
    lat: 17.53200, lng: 73.51800,
    coverImage: IMAGES.cafe8, images: JSON.stringify([IMAGES.cafe8, IMAGES.cafe5]),
    priceLevel: 2, wifiSpeedMbps: 50, wifiUploadMbps: 25, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.6, reviewCount: 58,
  }),

  base({
    name: 'O\\'Chef Cafe & Restaurant — Chiplun',
    slug: 'ochef-cafe-restaurant-chiplun',
    tagline: 'Top-rated cozy cafe in Chiplun — artisanal coffees, fresh Italian & great ambience.',
    description: 'One of Chiplun\'s most highly-rated cafes. Features comfortable booth seating, artisanal coffee preparations, pasta, and reliable WiFi for long working sessions.',
    address: 'City Center Market, Chiplun, Ratnagiri 415605',
    city: 'Ratnagiri', neighborhood: 'Chiplun',
    lat: 17.53450, lng: 73.52100,
    coverImage: IMAGES.cafe9, images: JSON.stringify([IMAGES.cafe9, IMAGES.cafe6]),
    priceLevel: 2, wifiSpeedMbps: 55, wifiUploadMbps: 28, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'QUIET', seatingComfort: 'COZY_COUCHES',
    hasAirConditioning: true, openLate: true, foodOptions: 'FULL_MENU',
    averageRating: 4.7, reviewCount: 64,
  }),

  base({
    name: 'Citrus Cafe (Lemon Tree Hotel) — Dapoli',
    slug: 'citrus-cafe-lemon-tree-dapoli',
    tagline: 'Bright all-day multi-cuisine coffee shop with high-speed fiber WiFi in Dapoli.',
    description: 'Bright and cheery 24/7 coffee shop in Lemon Tree Hotel Dapoli. Offers European, Indian, and Pan-Asian dishes with fast business-grade fiber WiFi and comfortable ergonomic seating.',
    address: 'Lemon Tree Hotel, Coastal Road, Dapoli, Ratnagiri 415712',
    city: 'Ratnagiri', neighborhood: 'Dapoli',
    lat: 17.75800, lng: 73.18900,
    phone: '+91 2358-280000',
    coverImage: IMAGES.cafe10, images: JSON.stringify([IMAGES.cafe10, IMAGES.cafe7]),
    priceLevel: 3, wifiSpeedMbps: 120, wifiUploadMbps: 90, wifiReliability: 'ROCK_SOLID',
    powerPlugDensity: 'AT_EVERY_SEAT', noiseLevel: 'SILENT', seatingComfort: 'ERGONOMIC',
    hasAirConditioning: true, hasMeetingRooms: true, openLate: true, specialtyCoffee: true,
    averageRating: 4.8, reviewCount: 72,
  }),

  base({
    name: 'Cafe Creme — Dapoli Camp',
    slug: 'cafe-creme-dapoli-camp',
    tagline: 'Dapoli Camp dessert cafe — chocolate cold coffee, milkshakes & study desks.',
    description: 'Situated in the central Dapoli Camp area. A favorite among local students and travelers for chocolate drinks, cold coffees, and light evening snacks with power outlets.',
    address: 'Camp Market, Dapoli, Ratnagiri 415712',
    city: 'Ratnagiri', neighborhood: 'Dapoli',
    lat: 17.75500, lng: 73.18700,
    coverImage: IMAGES.cafe1, images: JSON.stringify([IMAGES.cafe1, IMAGES.cafe9]),
    priceLevel: 1, wifiSpeedMbps: 40, wifiUploadMbps: 20, wifiReliability: 'STABLE',
    powerPlugDensity: 'PLENTIFUL', noiseLevel: 'MODERATE', seatingComfort: 'BASIC',
    hasAirConditioning: true, foodOptions: 'LIGHT_BITES',
    averageRating: 4.4, reviewCount: 36,
  }),
`;

// Replace the Ratnagiri section
const ratnagiriMarker = '// ── RATNAGIRI (user\'s city - full local coverage) ─────────────────────────';
const asiaMarker = '// ── ASIA-PACIFIC ──────────────────────────────────────────────────────────';

const startIdx = content.indexOf(ratnagiriMarker);
const endIdx = content.indexOf(asiaMarker);

if (startIdx !== -1 && endIdx !== -1) {
  content = content.slice(0, startIdx) + newRatnagiriCafes.trim() + '\n\n  ' + content.slice(endIdx);
  fs.writeFileSync(mockDataPath, content, 'utf8');
  console.log('Successfully expanded Ratnagiri cafes with 50+ real venues in mockData.ts!');
} else {
  console.error('Could not find marker positions in mockData.ts');
}
